require 'set'

# Отчистка последовательности
def clean_sequence(sequence)
  sequence.gsub(/[\s\d]/, '')
end

# Функция поиска минимальной специфичной последовательности
def find_min_unique_subsequence(a, b)
  min_unique = nil
  (1..a.length).each do |len|
    found = false
    seen = {}
    (0..a.length - len).each do |i|
      sub = a[i, len]
      next if seen[sub]
      seen[sub] = true
      unless b.include?(sub)
        min_unique = sub
        found = true
        break
      end
    end
    break if found
  end
  min_unique
end

# Функция поиска минимальной общей последовательности
def find_common_subsequence(a, b)
  (1..[a.length, b.length].min).each do |len|
    a.chars.each_cons(len) do |sub_arr|
      sub = sub_arr.join
      return sub if b.include?(sub)
    end
  end
  nil
end

# Функция поиска минимальной уникальносй последовательности
def find_min_unique(a, b, c)
  (1..a.length).each do |length|
    (0..a.length - length).each do |start_index|
      substring = a[start_index, length]
      unless b.include?(substring) || c.include?(substring)
        return substring
      end
    end
  end
  nil
end


# Наибольшая общая подпоследовательность
def longest_common_subsequence(a, b)
  max_common = ""
  (0...a.length).each do |i|
    ((i+max_common.length+1)...a.length).each do |j|
      sub = a[i...j]
      if (b.include?(sub))
        max_common = sub
      else
        break
      end
    end
  end
  max_common
end


covid_wuhan = clean_sequence("        1 attaaaggtt tataccttcc caggtaacaa accaaccaac tttcgatctc ttgtagatct
       61 gttctctaaa cgaactttaa aatctgtgtg gctgtcactc ggctgcatgc ttagtgcact
      121 cacgcagtat aattaataac taattactgt cgttgacagg acacgagtaa ctcgtctatc
      181 ttctgcaggc tgcttacggt ttcgtccgtg ttgcagccga tcatcagcac atctaggttt
      241 cgtccgggtg tgaccgaaag gtaagatgga gagccttgtc cctggtttca acgagaaaac
      301 acacgtccaa ctcagtttgc ctgttttaca ggttcgcgac gtgctcgtac gtggctttgg
      361 agactccgtg gaggaggtct tatcagaggc acgtcaacat cttaaagatg gcacttgtgg
      421 cttagtagaa gttgaaaaag gcgttttgcc tcaacttgaa cagccctatg tgttcatcaa
      481 acgttcggat gctcgaactg cacctcatgg tcatgttatg gttgagctgg tagcagaact
      541 cgaaggcatt cagtacggtc gtagtggtga gacacttggt gtccttgtcc ctcatgtggg
      601 cgaaatacca gtggcttacc gcaaggttct tcttcgtaag aacggtaata aaggagctgg
      661 tggccatagt tacggcgccg atctaaagtc atttgactta ggcgacgagc ttggcactga
      721 tccttatgaa gattttcaag aaaactggaa cactaaacat agcagtggtg ttacccgtga
      781 actcatgcgt gagcttaacg gaggggcata cactcgctat gtcgataaca acttctgtgg
      841 ccctgatggc taccctcttg agtgcattaa agaccttcta gcacgtgctg gtaaagcttc
      901 atgcactttg tccgaacaac tggactttat tgacactaag aggggtgtat actgctgccg
      961 tgaacatgag catgaaattg cttggtacac ggaacgttct gaaaagagct atgaattgca
     1021 gacacctttt gaaattaaat tggcaaagaa atttgacacc ttcaatgggg aatgtccaaa
     1081 ttttgtattt cccttaaatt ccataatcaa gactattcaa ccaagggttg aaaagaaaaa
     1141 gcttgatggc tttatgggta gaattcgatc tgtctatcca gttgcgtcac caaatgaatg
     1201 caaccaaatg tgcctttcaa ctctcatgaa gtgtgatcat tgtggtgaaa cttcatggca
     1261 gacgggcgat tttgttaaag ccacttgcga attttgtggc actgagaatt tgactaaaga
     1321 aggtgccact acttgtggtt acttacccca aaatgctgtt gttaaaattt attgtccagc
     1381 atgtcacaat tcagaagtag gacctgagca tagtcttgcc gaataccata atgaatctgg
     1441 cttgaaaacc attcttcgta agggtggtcg cactattgcc tttggaggct gtgtgttctc
     1501 ttatgttggt tgccataaca agtgtgccta ttgggttcca cgtgctagcg ctaacatagg
     1561 ttgtaaccat acaggtgttg ttggagaagg ttccgaaggt cttaatgaca accttcttga
     1621 aatactccaa aaagagaaag tcaacatcaa tattgttggt gactttaaac ttaatgaaga
     1681 gatcgccatt attttggcat ctttttctgc ttccacaagt gcttttgtgg aaactgtgaa
     1741 aggtttggat tataaagcat tcaaacaaat tgttgaatcc tgtggtaatt ttaaagttac
     1801 aaaaggaaaa gctaaaaaag gtgcctggaa tattggtgaa cagaaatcaa tactgagtcc
     1861 tctttatgca tttgcatcag aggctgctcg tgttgtacga tcaattttct cccgcactct
     1921 tgaaactgct caaaattctg tgcgtgtttt acagaaggcc gctataacaa tactagatgg
     1981 aatttcacag tattcactga gactcattga tgctatgatg ttcacatctg atttggctac
     2041 taacaatcta gttgtaatgg cctacattac aggtggtgtt gttcagttga cttcgcagtg
     2101 gctaactaac atctttggca ctgtttatga aaaactcaaa cccgtccttg attggcttga
     2161 agagaagttt aaggaaggtg tagagtttct tagagacggt tgggaaattg ttaaatttat
     2221 ctcaacctgt gcttgtgaaa ttgtcggtgg acaaattgtc acctgtgcaa aggaaattaa
     2281 ggagagtgtt cagacattct ttaagcttgt aaataaattt ttggctttgt gtgctgactc
     2341 tatcattatt ggtggagcta aacttaaagc cttgaattta ggtgaaacat ttgtcacgca
     2401 ctcaaaggga ttgtacagaa agtgtgttaa atccagagaa gaaactggcc tactcatgcc
     2461 tctaaaagcc ccaaaagaaa ttatcttctt agagggagaa acacttccca cagaagtgtt
     2521 aacagaggaa gttgtcttga aaactggtga tttacaacca ttagaacaac ctactagtga
     2581 agctgttgaa gctccattgg ttggtacacc agtttgtatt aacgggctta tgttgctcga
     2641 aatcaaagac acagaaaagt actgtgccct tgcacctaat atgatggtaa caaacaatac
     2701 cttcacactc aaaggcggtg caccaacaaa ggttactttt ggtgatgaca ctgtgataga
     2761 agtgcaaggt tacaagagtg tgaatatcac ttttgaactt gatgaaagga ttgataaagt
     2821 acttaatgag aagtgctctg cctatacagt tgaactcggt acagaagtaa atgagttcgc
     2881 ctgtgttgtg gcagatgctg tcataaaaac tttgcaacca gtatctgaat tacttacacc
     2941 actgggcatt gatttagatg agtggagtat ggctacatac tacttatttg atgagtctgg
     3001 tgagtttaaa ttggcttcac atatgtattg ttctttctac cctccagatg aggatgaaga
     3061 agaaggtgat tgtgaagaag aagagtttga gccatcaact caatatgagt atggtactga
     3121 agatgattac caaggtaaac ctttggaatt tggtgccact tctgctgctc ttcaacctga
     3181 agaagagcaa gaagaagatt ggttagatga tgatagtcaa caaactgttg gtcaacaaga
     3241 cggcagtgag gacaatcaga caactactat tcaaacaatt gttgaggttc aacctcaatt
     3301 agagatggaa cttacaccag ttgttcagac tattgaagtg aatagtttta gtggttattt
     3361 aaaacttact gacaatgtat acattaaaaa tgcagacatt gtggaagaag ctaaaaaggt
     3421 aaaaccaaca gtggttgtta atgcagccaa tgtttacctt aaacatggag gaggtgttgc
     3481 aggagcctta aataaggcta ctaacaatgc catgcaagtt gaatctgatg attacatagc
     3541 tactaatgga ccacttaaag tgggtggtag ttgtgtttta agcggacaca atcttgctaa
     3601 acactgtctt catgttgtcg gcccaaatgt taacaaaggt gaagacattc aacttcttaa
     3661 gagtgcttat gaaaatttta atcagcacga agttctactt gcaccattat tatcagctgg
     3721 tatttttggt gctgacccta tacattcttt aagagtttgt gtagatactg ttcgcacaaa
     3781 tgtctactta gctgtctttg ataaaaatct ctatgacaaa cttgtttcaa gctttttgga
     3841 aatgaagagt gaaaagcaag ttgaacaaaa gatcgctgag attcctaaag aggaagttaa
     3901 gccatttata actgaaagta aaccttcagt tgaacagaga aaacaagatg ataagaaaat
     3961 caaagcttgt gttgaagaag ttacaacaac tctggaagaa actaagttcc tcacagaaaa
     4021 cttgttactt tatattgaca ttaatggcaa tcttcatcca gattctgcca ctcttgttag
     4081 tgacattgac atcactttct taaagaaaga tgctccatat atagtgggtg atgttgttca
     4141 agagggtgtt ttaactgctg tggttatacc tactaaaaag gctggtggca ctactgaaat
     4201 gctagcgaaa gctttgagaa aagtgccaac agacaattat ataaccactt acccgggtca
     4261 gggtttaaat ggttacactg tagaggaggc aaagacagtg cttaaaaagt gtaaaagtgc
     4321 cttttacatt ctaccatcta ttatctctaa tgagaagcaa gaaattcttg gaactgtttc
     4381 ttggaatttg cgagaaatgc ttgcacatgc agaagaaaca cgcaaattaa tgcctgtctg
     4441 tgtggaaact aaagccatag tttcaactat acagcgtaaa tataagggta ttaaaataca
     4501 agagggtgtg gttgattatg gtgctagatt ttacttttac accagtaaaa caactgtagc
     4561 gtcacttatc aacacactta acgatctaaa tgaaactctt gttacaatgc cacttggcta
     4621 tgtaacacat ggcttaaatt tggaagaagc tgctcggtat atgagatctc tcaaagtgcc
     4681 agctacagtt tctgtttctt cacctgatgc tgttacagcg tataatggtt atcttacttc
     4741 ttcttctaaa acacctgaag aacattttat tgaaaccatc tcacttgctg gttcctataa
     4801 agattggtcc tattctggac aatctacaca actaggtata gaatttctta agagaggtga
     4861 taaaagtgta tattacacta gtaatcctac cacattccac ctagatggtg aagttatcac
     4921 ctttgacaat cttaagacac ttctttcttt gagagaagtg aggactatta aggtgtttac
     4981 aacagtagac aacattaacc tccacacgca agttgtggac atgtcaatga catatggaca
     5041 acagtttggt ccaacttatt tggatggagc tgatgttact aaaataaaac ctcataattc
     5101 acatgaaggt aaaacatttt atgttttacc taatgatgac actctacgtg ttgaggcttt
     5161 tgagtactac cacacaactg atcctagttt tctgggtagg tacatgtcag cattaaatca
     5221 cactaaaaag tggaaatacc cacaagttaa tggtttaact tctattaaat gggcagataa
     5281 caactgttat cttgccactg cattgttaac actccaacaa atagagttga agtttaatcc
     5341 acctgctcta caagatgctt attacagagc aagggctggt gaagctgcta acttttgtgc
     5401 acttatctta gcctactgta ataagacagt aggtgagtta ggtgatgtta gagaaacaat
     5461 gagttacttg tttcaacatg ccaatttaga ttcttgcaaa agagtcttga acgtggtgtg
     5521 taaaacttgt ggacaacagc agacaaccct taagggtgta gaagctgtta tgtacatggg
     5581 cacactttct tatgaacaat ttaagaaagg tgttcagata ccttgtacgt gtggtaaaca
     5641 agctacaaaa tatctagtac aacaggagtc accttttgtt atgatgtcag caccacctgc
     5701 tcagtatgaa cttaagcatg gtacatttac ttgtgctagt gagtacactg gtaattacca
     5761 gtgtggtcac tataaacata taacttctaa agaaactttg tattgcatag acggtgcttt
     5821 acttacaaag tcctcagaat acaaaggtcc tattacggat gttttctaca aagaaaacag
     5881 ttacacaaca accataaaac cagttactta taaattggat ggtgttgttt gtacagaaat
     5941 tgaccctaag ttggacaatt attataagaa agacaattct tatttcacag agcaaccaat
     6001 tgatcttgta ccaaaccaac catatccaaa cgcaagcttc gataatttta agtttgtatg
     6061 tgataatatc aaatttgctg atgatttaaa ccagttaact ggttataaga aacctgcttc
     6121 aagagagctt aaagttacat ttttccctga cttaaatggt gatgtggtgg ctattgatta
     6181 taaacactac acaccctctt ttaagaaagg agctaaattg ttacataaac ctattgtttg
     6241 gcatgttaac aatgcaacta ataaagccac gtataaacca aatacctggt gtatacgttg
     6301 tctttggagc acaaaaccag ttgaaacatc aaattcgttt gatgtactga agtcagagga
     6361 cgcgcaggga atggataatc ttgcctgcga agatctaaaa ccagtctctg aagaagtagt
     6421 ggaaaatcct accatacaga aagacgttct tgagtgtaat gtgaaaacta ccgaagttgt
     6481 aggagacatt atacttaaac cagcaaataa tagtttaaaa attacagaag aggttggcca
     6541 cacagatcta atggctgctt atgtagacaa ttctagtctt actattaaga aacctaatga
     6601 attatctaga gtattaggtt tgaaaaccct tgctactcat ggtttagctg ctgttaatag
     6661 tgtcccttgg gatactatag ctaattatgc taagcctttt cttaacaaag ttgttagtac
     6721 aactactaac atagttacac ggtgtttaaa ccgtgtttgt actaattata tgccttattt
     6781 ctttacttta ttgctacaat tgtgtacttt tactagaagt acaaattcta gaattaaagc
     6841 atctatgccg actactatag caaagaatac tgttaagagt gtcggtaaat tttgtctaga
     6901 ggcttcattt aattatttga agtcacctaa tttttctaaa ctgataaata ttataatttg
     6961 gtttttacta ttaagtgttt gcctaggttc tttaatctac tcaaccgctg ctttaggtgt
     7021 tttaatgtct aatttaggca tgccttctta ctgtactggt tacagagaag gctatttgaa
     7081 ctctactaat gtcactattg caacctactg tactggttct ataccttgta gtgtttgtct
     7141 tagtggttta gattctttag acacctatcc ttctttagaa actatacaaa ttaccatttc
     7201 atcttttaaa tgggatttaa ctgcttttgg cttagttgca gagtggtttt tggcatatat
     7261 tcttttcact aggtttttct atgtacttgg attggctgca atcatgcaat tgtttttcag
     7321 ctattttgca gtacatttta ttagtaattc ttggcttatg tggttaataa ttaatcttgt
     7381 acaaatggcc ccgatttcag ctatggttag aatgtacatc ttctttgcat cattttatta
     7441 tgtatggaaa agttatgtgc atgttgtaga cggttgtaat tcatcaactt gtatgatgtg
     7501 ttacaaacgt aatagagcaa caagagtcga atgtacaact attgttaatg gtgttagaag
     7561 gtccttttat gtctatgcta atggaggtaa aggcttttgc aaactacaca attggaattg
     7621 tgttaattgt gatacattct gtgctggtag tacatttatt agtgatgaag ttgcgagaga
     7681 cttgtcacta cagtttaaaa gaccaataaa tcctactgac cagtcttctt acatcgttga
     7741 tagtgttaca gtgaagaatg gttccatcca tctttacttt gataaagctg gtcaaaagac
     7801 ttatgaaaga cattctctct ctcattttgt taacttagac aacctgagag ctaataacac
     7861 taaaggttca ttgcctatta atgttatagt ttttgatggt aaatcaaaat gtgaagaatc
     7921 atctgcaaaa tcagcgtctg tttactacag tcagcttatg tgtcaaccta tactgttact
     7981 agatcaggca ttagtgtctg atgttggtga tagtgcggaa gttgcagtta aaatgtttga
     8041 tgcttacgtt aatacgtttt catcaacttt taacgtacca atggaaaaac tcaaaacact
     8101 agttgcaact gcagaagctg aacttgcaaa gaatgtgtcc ttagacaatg tcttatctac
     8161 ttttatttca gcagctcggc aagggtttgt tgattcagat gtagaaacta aagatgttgt
     8221 tgaatgtctt aaattgtcac atcaatctga catagaagtt actggcgata gttgtaataa
     8281 ctatatgctc acctataaca aagttgaaaa catgacaccc cgtgaccttg gtgcttgtat
     8341 tgactgtagt gcgcgtcata ttaatgcgca ggtagcaaaa agtcacaaca ttgctttgat
     8401 atggaacgtt aaagatttca tgtcattgtc tgaacaacta cgaaaacaaa tacgtagtgc
     8461 tgctaaaaag aataacttac cttttaagtt gacatgtgca actactagac aagttgttaa
     8521 tgttgtaaca acaaagatag cacttaaggg tggtaaaatt gttaataatt ggttgaagca
     8581 gttaattaaa gttacacttg tgttcctttt tgttgctgct attttctatt taataacacc
     8641 tgttcatgtc atgtctaaac atactgactt ttcaagtgaa atcataggat acaaggctat
     8701 tgatggtggt gtcactcgtg acatagcatc tacagatact tgttttgcta acaaacatgc
     8761 tgattttgac acatggttta gccagcgtgg tggtagttat actaatgaca aagcttgccc
     8821 attgattgct gcagtcataa caagagaagt gggttttgtc gtgcctggtt tgcctggcac
     8881 gatattacgc acaactaatg gtgacttttt gcatttctta cctagagttt ttagtgcagt
     8941 tggtaacatc tgttacacac catcaaaact tatagagtac actgactttg caacatcagc
     9001 ttgtgttttg gctgctgaat gtacaatttt taaagatgct tctggtaagc cagtaccata
     9061 ttgttatgat accaatgtac tagaaggttc tgttgcttat gaaagtttac gccctgacac
     9121 acgttatgtg ctcatggatg gctctattat tcaatttcct aacacctacc ttgaaggttc
     9181 tgttagagtg gtaacaactt ttgattctga gtactgtagg cacggcactt gtgaaagatc
     9241 agaagctggt gtttgtgtat ctactagtgg tagatgggta cttaacaatg attattacag
     9301 atctttacca ggagttttct gtggtgtaga tgctgtaaat ttacttacta atatgtttac
     9361 accactaatt caacctattg gtgctttgga catatcagca tctatagtag ctggtggtat
     9421 tgtagctatc gtagtaacat gccttgccta ctattttatg aggtttagaa gagcttttgg
     9481 tgaatacagt catgtagttg cctttaatac tttactattc cttatgtcat tcactgtact
     9541 ctgtttaaca ccagtttact cattcttacc tggtgtttat tctgttattt acttgtactt
     9601 gacattttat cttactaatg atgtttcttt tttagcacat attcagtgga tggttatgtt
     9661 cacaccttta gtacctttct ggataacaat tgcttatatc atttgtattt ccacaaagca
     9721 tttctattgg ttctttagta attacctaaa gagacgtgta gtctttaatg gtgtttcctt
     9781 tagtactttt gaagaagctg cgctgtgcac ctttttgtta aataaagaaa tgtatctaaa
     9841 gttgcgtagt gatgtgctat tacctcttac gcaatataat agatacttag ctctttataa
     9901 taagtacaag tattttagtg gagcaatgga tacaactagc tacagagaag ctgcttgttg
     9961 tcatctcgca aaggctctca atgacttcag taactcaggt tctgatgttc tttaccaacc
    10021 accacaaacc tctatcacct cagctgtttt gcagagtggt tttagaaaaa tggcattccc
    10081 atctggtaaa gttgagggtt gtatggtaca agtaacttgt ggtacaacta cacttaacgg
    10141 tctttggctt gatgacgtag tttactgtcc aagacatgtg atctgcacct ctgaagacat
    10201 gcttaaccct aattatgaag atttactcat tcgtaagtct aatcataatt tcttggtaca
    10261 ggctggtaat gttcaactca gggttattgg acattctatg caaaattgtg tacttaagct
    10321 taaggttgat acagccaatc ctaagacacc taagtataag tttgttcgca ttcaaccagg
    10381 acagactttt tcagtgttag cttgttacaa tggttcacca tctggtgttt accaatgtgc
    10441 tatgaggccc aatttcacta ttaagggttc attccttaat ggttcatgtg gtagtgttgg
    10501 ttttaacata gattatgact gtgtctcttt ttgttacatg caccatatgg aattaccaac
    10561 tggagttcat gctggcacag acttagaagg taacttttat ggaccttttg ttgacaggca
    10621 aacagcacaa gcagctggta cggacacaac tattacagtt aatgttttag cttggttgta
    10681 cgctgctgtt ataaatggag acaggtggtt tctcaatcga tttaccacaa ctcttaatga
    10741 ctttaacctt gtggctatga agtacaatta tgaacctcta acacaagacc atgttgacat
    10801 actaggacct ctttctgctc aaactggaat tgccgtttta gatatgtgtg cttcattaaa
    10861 agaattactg caaaatggta tgaatggacg taccatattg ggtagtgctt tattagaaga
    10921 tgaatttaca ccttttgatg ttgttagaca atgctcaggt gttactttcc aaagtgcagt
    10981 gaaaagaaca atcaagggta cacaccactg gttgttactc acaattttga cttcactttt
    11041 agttttagtc cagagtactc aatggtcttt gttctttttt ttgtatgaaa atgccttttt
    11101 accttttgct atgggtatta ttgctatgtc tgcttttgca atgatgtttg tcaaacataa
    11161 gcatgcattt ctctgtttgt ttttgttacc ttctcttgcc actgtagctt attttaatat
    11221 ggtctatatg cctgctagtt gggtgatgcg tattatgaca tggttggata tggttgatac
    11281 tagtttgtct ggttttaagc taaaagactg tgttatgtat gcatcagctg tagtgttact
    11341 aatccttatg acagcaagaa ctgtgtatga tgatggtgct aggagagtgt ggacacttat
    11401 gaatgtcttg acactcgttt ataaagttta ttatggtaat gctttagatc aagccatttc
    11461 catgtgggct cttataatct ctgttacttc taactactca ggtgtagtta caactgtcat
    11521 gtttttggcc agaggtattg tttttatgtg tgttgagtat tgccctattt tcttcataac
    11581 tggtaataca cttcagtgta taatgctagt ttattgtttc ttaggctatt tttgtacttg
    11641 ttactttggc ctcttttgtt tactcaaccg ctactttaga ctgactcttg gtgtttatga
    11701 ttacttagtt tctacacagg agtttagata tatgaattca cagggactac tcccacccaa
    11761 gaatagcata gatgccttca aactcaacat taaattgttg ggtgttggtg gcaaaccttg
    11821 tatcaaagta gccactgtac agtctaaaat gtcagatgta aagtgcacat cagtagtctt
    11881 actctcagtt ttgcaacaac tcagagtaga atcatcatct aaattgtggg ctcaatgtgt
    11941 ccagttacac aatgacattc tcttagctaa agatactact gaagcctttg aaaaaatggt
    12001 ttcactactt tctgttttgc tttccatgca gggtgctgta gacataaaca agctttgtga
    12061 agaaatgctg gacaacaggg caaccttaca agctatagcc tcagagttta gttcccttcc
    12121 atcatatgca gcttttgcta ctgctcaaga agcttatgag caggctgttg ctaatggtga
    12181 ttctgaagtt gttcttaaaa agttgaagaa gtctttgaat gtggctaaat ctgaatttga
    12241 ccgtgatgca gccatgcaac gtaagttgga aaagatggct gatcaagcta tgacccaaat
    12301 gtataaacag gctagatctg aggacaagag ggcaaaagtt actagtgcta tgcagacaat
    12361 gcttttcact atgcttagaa agttggataa tgatgcactc aacaacatta tcaacaatgc
    12421 aagagatggt tgtgttccct tgaacataat acctcttaca acagcagcca aactaatggt
    12481 tgtcatacca gactataaca catataaaaa tacgtgtgat ggtacaacat ttacttatgc
    12541 atcagcattg tgggaaatcc aacaggttgt agatgcagat agtaaaattg ttcaacttag
    12601 tgaaattagt atggacaatt cacctaattt agcatggcct cttattgtaa cagctttaag
    12661 ggccaattct gctgtcaaat tacagaataa tgagcttagt cctgttgcac tacgacagat
    12721 gtcttgtgct gccggtacta cacaaactgc ttgcactgat gacaatgcgt tagcttacta
    12781 caacacaaca aagggaggta ggtttgtact tgcactgtta tccgatttac aggatttgaa
    12841 atgggctaga ttccctaaga gtgatggaac tggtactatc tatacagaac tggaaccacc
    12901 ttgtaggttt gttacagaca cacctaaagg tcctaaagtg aagtatttat actttattaa
    12961 aggattaaac aacctaaata gaggtatggt acttggtagt ttagctgcca cagtacgtct
    13021 acaagctggt aatgcaacag aagtgcctgc caattcaact gtattatctt tctgtgcttt
    13081 tgctgtagat gctgctaaag cttacaaaga ttatctagct agtgggggac aaccaatcac
    13141 taattgtgtt aagatgttgt gtacacacac tggtactggt caggcaataa cagttacacc
    13201 ggaagccaat atggatcaag aatcctttgg tggtgcatcg tgttgtctgt actgccgttg
    13261 ccacatagat catccaaatc ctaaaggatt ttgtgactta aaaggtaagt atgtacaaat
    13321 acctacaact tgtgctaatg accctgtggg ttttacactt aaaaacacag tctgtaccgt
    13381 ctgcggtatg tggaaaggtt atggctgtag ttgtgatcaa ctccgcgaac ccatgcttca
    13441 gtcagctgat gcacaatcgt ttttaaacgg gtttgcggtg taagtgcagc ccgtcttaca
    13501 ccgtgcggca caggcactag tactgatgtc gtatacaggg cttttgacat ctacaatgat
    13561 aaagtagctg gttttgctaa attcctaaaa actaattgtt gtcgcttcca agaaaaggac
    13621 gaagatgaca atttaattga ttcttacttt gtagttaaga gacacacttt ctctaactac
    13681 caacatgaag aaacaattta taatttactt aaggattgtc cagctgttgc taaacatgac
    13741 ttctttaagt ttagaataga cggtgacatg gtaccacata tatcacgtca acgtcttact
    13801 aaatacacaa tggcagacct cgtctatgct ttaaggcatt ttgatgaagg taattgtgac
    13861 acattaaaag aaatacttgt cacatacaat tgttgtgatg atgattattt caataaaaag
    13921 gactggtatg attttgtaga aaacccagat atattacgcg tatacgccaa cttaggtgaa
    13981 cgtgtacgcc aagctttgtt aaaaacagta caattctgtg atgccatgcg aaatgctggt
    14041 attgttggtg tactgacatt agataatcaa gatctcaatg gtaactggta tgatttcggt
    14101 gatttcatac aaaccacgcc aggtagtgga gttcctgttg tagattctta ttattcattg
    14161 ttaatgccta tattaacctt gaccagggct ttaactgcag agtcacatgt tgacactgac
    14221 ttaacaaagc cttacattaa gtgggatttg ttaaaatatg acttcacgga agagaggtta
    14281 aaactctttg accgttattt taaatattgg gatcagacat accacccaaa ttgtgttaac
    14341 tgtttggatg acagatgcat tctgcattgt gcaaacttta atgttttatt ctctacagtg
    14401 ttcccaccta caagttttgg accactagtg agaaaaatat ttgttgatgg tgttccattt
    14461 gtagtttcaa ctggatacca cttcagagag ctaggtgttg tacataatca ggatgtaaac
    14521 ttacatagct ctagacttag ttttaaggaa ttacttgtgt atgctgctga ccctgctatg
    14581 cacgctgctt ctggtaatct attactagat aaacgcacta cgtgcttttc agtagctgca
    14641 cttactaaca atgttgcttt tcaaactgtc aaacccggta attttaacaa agacttctat
    14701 gactttgctg tgtctaaggg tttctttaag gaaggaagtt ctgttgaatt aaaacacttc
    14761 ttctttgctc aggatggtaa tgctgctatc agcgattatg actactatcg ttataatcta
    14821 ccaacaatgt gtgatatcag acaactacta tttgtagttg aagttgttga taagtacttt
    14881 gattgttacg atggtggctg tattaatgct aaccaagtca tcgtcaacaa cctagacaaa
    14941 tcagctggtt ttccatttaa taaatggggt aaggctagac tttattatga ttcaatgagt
    15001 tatgaggatc aagatgcact tttcgcatat acaaaacgta atgtcatccc tactataact
    15061 caaatgaatc ttaagtatgc cattagtgca aagaatagag ctcgcaccgt agctggtgtc
    15121 tctatctgta gtactatgac caatagacag tttcatcaaa aattattgaa atcaatagcc
    15181 gccactagag gagctactgt agtaattgga acaagcaaat tctatggtgg ttggcacaac
    15241 atgttaaaaa ctgtttatag tgatgtagaa aaccctcacc ttatgggttg ggattatcct
    15301 aaatgtgata gagccatgcc taacatgctt agaattatgg cctcacttgt tcttgctcgc
    15361 aaacatacaa cgtgttgtag cttgtcacac cgtttctata gattagctaa tgagtgtgct
    15421 caagtattga gtgaaatggt catgtgtggc ggttcactat atgttaaacc aggtggaacc
    15481 tcatcaggag atgccacaac tgcttatgct aatagtgttt ttaacatttg tcaagctgtc
    15541 acggccaatg ttaatgcact tttatctact gatggtaaca aaattgccga taagtatgtc
    15601 cgcaatttac aacacagact ttatgagtgt ctctatagaa atagagatgt tgacacagac
    15661 tttgtgaatg agttttacgc atatttgcgt aaacatttct caatgatgat actctctgac
    15721 gatgctgttg tgtgtttcaa tagcacttat gcatctcaag gtctagtggc tagcataaag
    15781 aactttaagt cagttcttta ttatcaaaac aatgttttta tgtctgaagc aaaatgttgg
    15841 actgagactg accttactaa aggacctcat gaattttgct ctcaacatac aatgctagtt
    15901 aaacagggtg atgattatgt gtaccttcct tacccagatc catcaagaat cctaggggcc
    15961 ggctgttttg tagatgatat cgtaaaaaca gatggtacac ttatgattga acggttcgtg
    16021 tctttagcta tagatgctta cccacttact aaacatccta atcaggagta tgctgatgtc
    16081 tttcatttgt acttacaata cataagaaag ctacatgatg agttaacagg acacatgtta
    16141 gacatgtatt ctgttatgct tactaatgat aacacttcaa ggtattggga acctgagttt
    16201 tatgaggcta tgtacacacc gcatacagtc ttacaggctg ttggggcttg tgttctttgc
    16261 aattcacaga cttcattaag atgtggtgct tgcatacgta gaccattctt atgttgtaaa
    16321 tgctgttacg accatgtcat atcaacatca cataaattag tcttgtctgt taatccgtat
    16381 gtttgcaatg ctccaggttg tgatgtcaca gatgtgactc aactttactt aggaggtatg
    16441 agctattatt gtaaatcaca taaaccaccc attagttttc cattgtgtgc taatggacaa
    16501 gtttttggtt tatataaaaa tacatgtgtt ggtagcgata atgttactga ctttaatgca
    16561 attgcaacat gtgactggac aaatgctggt gattacattt tagctaacac ctgtactgaa
    16621 agactcaagc tttttgcagc agaaacgctc aaagctactg aggagacatt taaactgtct
    16681 tatggtattg ctactgtacg tgaagtgctg tctgacagag aattacatct ttcatgggaa
    16741 gttggtaaac ctagaccacc acttaaccga aattatgtct ttactggtta tcgtgtaact
    16801 aaaaacagta aagtacaaat aggagagtac acctttgaaa aaggtgacta tggtgatgct
    16861 gttgtttacc gaggtacaac aacttacaaa ttaaatgttg gtgattattt tgtgctgaca
    16921 tcacatacag taatgccatt aagtgcacct acactagtgc cacaagagca ctatgttaga
    16981 attactggct tatacccaac actcaatatc tcagatgagt tttctagcaa tgttgcaaat
    17041 tatcaaaagg ttggtatgca aaagtattct acactccagg gaccacctgg tactggtaag
    17101 agtcattttg ctattggcct agctctctac tacccttctg ctcgcatagt gtatacagct
    17161 tgctctcatg ccgctgttga tgcactatgt gagaaggcat taaaatattt gcctatagat
    17221 aaatgtagta gaattatacc tgcacgtgct cgtgtagagt gttttgataa attcaaagtg
    17281 aattcaacat tagaacagta tgtcttttgt actgtaaatg cattgcctga gacgacagca
    17341 gatatagttg tctttgatga aatttcaatg gccacaaatt atgatttgag tgttgtcaat
    17401 gccagattac gtgctaagca ctatgtgtac attggcgacc ctgctcaatt acctgcacca
    17461 cgcacattgc taactaaggg cacactagaa ccagaatatt tcaattcagt gtgtagactt
    17521 atgaaaacta taggtccaga catgttcctc ggaacttgtc ggcgttgtcc tgctgaaatt
    17581 gttgacactg tgagtgcttt ggtttatgat aataagctta aagcacataa agacaaatca
    17641 gctcaatgct ttaaaatgtt ttataagggt gttatcacgc atgatgtttc atctgcaatt
    17701 aacaggccac aaataggcgt ggtaagagaa ttccttacac gtaaccctgc ttggagaaaa
    17761 gctgtcttta tttcacctta taattcacag aatgctgtag cctcaaagat tttgggacta
    17821 ccaactcaaa ctgttgattc atcacagggc tcagaatatg actatgtcat attcactcaa
    17881 accactgaaa cagctcactc ttgtaatgta aacagattta atgttgctat taccagagca
    17941 aaagtaggca tactttgcat aatgtctgat agagaccttt atgacaagtt gcaatttaca
    18001 agtcttgaaa ttccacgtag gaatgtggca actttacaag ctgaaaatgt aacaggactc
    18061 tttaaagatt gtagtaaggt aatcactggg ttacatccta cacaggcacc tacacacctc
    18121 agtgttgaca ctaaattcaa aactgaaggt ttatgtgttg acatacctgg catacctaag
    18181 gacatgacct atagaagact catctctatg atgggtttta aaatgaatta tcaagttaat
    18241 ggttacccta acatgtttat cacccgcgaa gaagctataa gacatgtacg tgcatggatt
    18301 ggcttcgatg tcgaggggtg tcatgctact agagaagctg ttggtaccaa tttaccttta
    18361 cagctaggtt tttctacagg tgttaaccta gttgctgtac ctacaggtta tgttgataca
    18421 cctaataata cagatttttc cagagttagt gctaaaccac cgcctggaga tcaatttaaa
    18481 cacctcatac cacttatgta caaaggactt ccttggaatg tagtgcgtat aaagattgta
    18541 caaatgttaa gtgacacact taaaaatctc tctgacagag tcgtatttgt cttatgggca
    18601 catggctttg agttgacatc tatgaagtat tttgtgaaaa taggacctga gcgcacctgt
    18661 tgtctatgtg atagacgtgc cacatgcttt tccactgctt cagacactta tgcctgttgg
    18721 catcattcta ttggatttga ttacgtctat aatccgttta tgattgatgt tcaacaatgg
    18781 ggttttacag gtaacctaca aagcaaccat gatctgtatt gtcaagtcca tggtaatgca
    18841 catgtagcta gttgtgatgc aatcatgact aggtgtctag ctgtccacga gtgctttgtt
    18901 aagcgtgttg actggactat tgaatatcct ataattggtg atgaactgaa gattaatgcg
    18961 gcttgtagaa aggttcaaca catggttgtt aaagctgcat tattagcaga caaattccca
    19021 gttcttcacg acattggtaa ccctaaagct attaagtgtg tacctcaagc tgatgtagaa
    19081 tggaagttct atgatgcaca gccttgtagt gacaaagctt ataaaataga agaattattc
    19141 tattcttatg ccacacattc tgacaaattc acagatggtg tatgcctatt ttggaattgc
    19201 aatgtcgata gatatcctgc taattccatt gtttgtagat ttgacactag agtgctatct
    19261 aaccttaact tgcctggttg tgatggtggc agtttgtatg taaataaaca tgcattccac
    19321 acaccagctt ttgataaaag tgcttttgtt aatttaaaac aattaccatt tttctattac
    19381 tctgacagtc catgtgagtc tcatggaaaa caagtagtgt cagatataga ttatgtacca
    19441 ctaaagtctg ctacgtgtat aacacgttgc aatttaggtg gtgctgtctg tagacatcat
    19501 gctaatgagt acagattgta tctcgatgct tataacatga tgatctcagc tggctttagc
    19561 ttgtgggttt acaaacaatt tgatacttat aacctctgga acacttttac aagacttcag
    19621 agtttagaaa atgtggcttt taatgttgta aataagggac actttgatgg acaacagggt
    19681 gaagtaccag tttctatcat taataacact gtttacacaa aagttgatgg tgttgatgta
    19741 gaattgtttg aaaataaaac aacattacct gttaatgtag catttgagct ttgggctaag
    19801 cgcaacatta aaccagtacc agaggtgaaa atactcaata atttgggtgt ggacattgct
    19861 gctaatactg tgatctggga ctacaaaaga gatgctccag cacatatatc tactattggt
    19921 gtttgttcta tgactgacat agccaagaaa ccaactgaaa cgatttgtgc accactcact
    19981 gtcttttttg atggtagagt tgatggtcaa gtagacttat ttagaaatgc ccgtaatggt
    20041 gttcttatta cagaaggtag tgttaaaggt ttacaaccat ctgtaggtcc caaacaagct
    20101 agtcttaatg gagtcacatt aattggagaa gccgtaaaaa cacagttcaa ttattataag
    20161 aaagttgatg gtgttgtcca acaattacct gaaacttact ttactcagag tagaaattta
    20221 caagaattta aacccaggag tcaaatggaa attgatttct tagaattagc tatggatgaa
    20281 ttcattgaac ggtataaatt agaaggctat gccttcgaac atatcgttta tggagatttt
    20341 agtcatagtc agttaggtgg tttacatcta ctgattggac tagctaaacg ttttaaggaa
    20401 tcaccttttg aattagaaga ttttattcct atggacagta cagttaaaaa ctatttcata
    20461 acagatgcgc aaacaggttc atctaagtgt gtgtgttctg ttattgattt attacttgat
    20521 gattttgttg aaataataaa atcccaagat ttatctgtag tttctaaggt tgtcaaagtg
    20581 actattgact atacagaaat ttcatttatg ctttggtgta aagatggcca tgtagaaaca
    20641 ttttacccaa aattacaatc tagtcaagcg tggcaaccgg gtgttgctat gcctaatctt
    20701 tacaaaatgc aaagaatgct attagaaaag tgtgaccttc aaaattatgg tgatagtgca
    20761 acattaccta aaggcataat gatgaatgtc gcaaaatata ctcaactgtg tcaatattta
    20821 aacacattaa cattagctgt accctataat atgagagtta tacattttgg tgctggttct
    20881 gataaaggag ttgcaccagg tacagctgtt ttaagacagt ggttgcctac gggtacgctg
    20941 cttgtcgatt cagatcttaa tgactttgtc tctgatgcag attcaacttt gattggtgat
    21001 tgtgcaactg tacatacagc taataaatgg gatctcatta ttagtgatat gtacgaccct
    21061 aagactaaaa atgttacaaa agaaaatgac tctaaagagg gttttttcac ttacatttgt
    21121 gggtttatac aacaaaagct agctcttgga ggttccgtgg ctataaagat aacagaacat
    21181 tcttggaatg ctgatcttta taagctcatg ggacacttcg catggtggac agcctttgtt
    21241 actaatgtga atgcgtcatc atctgaagca tttttaattg gatgtaatta tcttggcaaa
    21301 ccacgcgaac aaatagatgg ttatgtcatg catgcaaatt acatattttg gaggaataca
    21361 aatccaattc agttgtcttc ctattcttta tttgacatga gtaaatttcc ccttaaatta
    21421 aggggtactg ctgttatgtc tttaaaagaa ggtcaaatca atgatatgat tttatctctt
    21481 cttagtaaag gtagacttat aattagagaa aacaacagag ttgttatttc tagtgatgtt
    21541 cttgttaaca actaaacgaa caatgtttgt ttttcttgtt ttattgccac tagtctctag
    21601 tcagtgtgtt aatcttacaa ccagaactca attaccccct gcatacacta attctttcac
    21661 acgtggtgtt tattaccctg acaaagtttt cagatcctca gttttacatt caactcagga
    21721 cttgttctta cctttctttt ccaatgttac ttggttccat gctatacatg tctctgggac
    21781 caatggtact aagaggtttg ataaccctgt cctaccattt aatgatggtg tttattttgc
    21841 ttccactgag aagtctaaca taataagagg ctggattttt ggtactactt tagattcgaa
    21901 gacccagtcc ctacttattg ttaataacgc tactaatgtt gttattaaag tctgtgaatt
    21961 tcaattttgt aatgatccat ttttgggtgt ttattaccac aaaaacaaca aaagttggat
    22021 ggaaagtgag ttcagagttt attctagtgc gaataattgc acttttgaat atgtctctca
    22081 gccttttctt atggaccttg aaggaaaaca gggtaatttc aaaaatctta gggaatttgt
    22141 gtttaagaat attgatggtt attttaaaat atattctaag cacacgccta ttaatttagt
    22201 gcgtgatctc cctcagggtt tttcggcttt agaaccattg gtagatttgc caataggtat
    22261 taacatcact aggtttcaaa ctttacttgc tttacataga agttatttga ctcctggtga
    22321 ttcttcttca ggttggacag ctggtgctgc agcttattat gtgggttatc ttcaacctag
    22381 gacttttcta ttaaaatata atgaaaatgg aaccattaca gatgctgtag actgtgcact
    22441 tgaccctctc tcagaaacaa agtgtacgtt gaaatccttc actgtagaaa aaggaatcta
    22501 tcaaacttct aactttagag tccaaccaac agaatctatt gttagatttc ctaatattac
    22561 aaacttgtgc ccttttggtg aagtttttaa cgccaccaga tttgcatctg tttatgcttg
    22621 gaacaggaag agaatcagca actgtgttgc tgattattct gtcctatata attccgcatc
    22681 attttccact tttaagtgtt atggagtgtc tcctactaaa ttaaatgatc tctgctttac
    22741 taatgtctat gcagattcat ttgtaattag aggtgatgaa gtcagacaaa tcgctccagg
    22801 gcaaactgga aagattgctg attataatta taaattacca gatgatttta caggctgcgt
    22861 tatagcttgg aattctaaca atcttgattc taaggttggt ggtaattata attacctgta
    22921 tagattgttt aggaagtcta atctcaaacc ttttgagaga gatatttcaa ctgaaatcta
    22981 tcaggccggt agcacacctt gtaatggtgt tgaaggtttt aattgttact ttcctttaca
    23041 atcatatggt ttccaaccca ctaatggtgt tggttaccaa ccatacagag tagtagtact
    23101 ttcttttgaa cttctacatg caccagcaac tgtttgtgga cctaaaaagt ctactaattt
    23161 ggttaaaaac aaatgtgtca atttcaactt caatggttta acaggcacag gtgttcttac
    23221 tgagtctaac aaaaagtttc tgcctttcca acaatttggc agagacattg ctgacactac
    23281 tgatgctgtc cgtgatccac agacacttga gattcttgac attacaccat gttcttttgg
    23341 tggtgtcagt gttataacac caggaacaaa tacttctaac caggttgctg ttctttatca
    23401 ggatgttaac tgcacagaag tccctgttgc tattcatgca gatcaactta ctcctacttg
    23461 gcgtgtttat tctacaggtt ctaatgtttt tcaaacacgt gcaggctgtt taataggggc
    23521 tgaacatgtc aacaactcat atgagtgtga catacccatt ggtgcaggta tatgcgctag
    23581 ttatcagact cagactaatt ctcctcggcg ggcacgtagt gtagctagtc aatccatcat
    23641 tgcctacact atgtcacttg gtgcagaaaa ttcagttgct tactctaata actctattgc
    23701 catacccaca aattttacta ttagtgttac cacagaaatt ctaccagtgt ctatgaccaa
    23761 gacatcagta gattgtacaa tgtacatttg tggtgattca actgaatgca gcaatctttt
    23821 gttgcaatat ggcagttttt gtacacaatt aaaccgtgct ttaactggaa tagctgttga
    23881 acaagacaaa aacacccaag aagtttttgc acaagtcaaa caaatttaca aaacaccacc
    23941 aattaaagat tttggtggtt ttaatttttc acaaatatta ccagatccat caaaaccaag
    24001 caagaggtca tttattgaag atctactttt caacaaagtg acacttgcag atgctggctt
    24061 catcaaacaa tatggtgatt gccttggtga tattgctgct agagacctca tttgtgcaca
    24121 aaagtttaac ggccttactg ttttgccacc tttgctcaca gatgaaatga ttgctcaata
    24181 cacttctgca ctgttagcgg gtacaatcac ttctggttgg acctttggtg caggtgctgc
    24241 attacaaata ccatttgcta tgcaaatggc ttataggttt aatggtattg gagttacaca
    24301 gaatgttctc tatgagaacc aaaaattgat tgccaaccaa tttaatagtg ctattggcaa
    24361 aattcaagac tcactttctt ccacagcaag tgcacttgga aaacttcaag atgtggtcaa
    24421 ccaaaatgca caagctttaa acacgcttgt taaacaactt agctccaatt ttggtgcaat
    24481 ttcaagtgtt ttaaatgata tcctttcacg tcttgacaaa gttgaggctg aagtgcaaat
    24541 tgataggttg atcacaggca gacttcaaag tttgcagaca tatgtgactc aacaattaat
    24601 tagagctgca gaaatcagag cttctgctaa tcttgctgct actaaaatgt cagagtgtgt
    24661 acttggacaa tcaaaaagag ttgatttttg tggaaagggc tatcatctta tgtccttccc
    24721 tcagtcagca cctcatggtg tagtcttctt gcatgtgact tatgtccctg cacaagaaaa
    24781 gaacttcaca actgctcctg ccatttgtca tgatggaaaa gcacactttc ctcgtgaagg
    24841 tgtctttgtt tcaaatggca cacactggtt tgtaacacaa aggaattttt atgaaccaca
    24901 aatcattact acagacaaca catttgtgtc tggtaactgt gatgttgtaa taggaattgt
    24961 caacaacaca gtttatgatc ctttgcaacc tgaattagac tcattcaagg aggagttaga
    25021 taaatatttt aagaatcata catcaccaga tgttgattta ggtgacatct ctggcattaa
    25081 tgcttcagtt gtaaacattc aaaaagaaat tgaccgcctc aatgaggttg ccaagaattt
    25141 aaatgaatct ctcatcgatc tccaagaact tggaaagtat gagcagtata taaaatggcc
    25201 atggtacatt tggctaggtt ttatagctgg cttgattgcc atagtaatgg tgacaattat
    25261 gctttgctgt atgaccagtt gctgtagttg tctcaagggc tgttgttctt gtggatcctg
    25321 ctgcaaattt gatgaagacg actctgagcc agtgctcaaa ggagtcaaat tacattacac
    25381 ataaacgaac ttatggattt gtttatgaga atcttcacaa ttggaactgt aactttgaag
    25441 caaggtgaaa tcaaggatgc tactccttca gattttgttc gcgctactgc aacgataccg
    25501 atacaagcct cactcccttt cggatggctt attgttggcg ttgcacttct tgctgttttt
    25561 cagagcgctt ccaaaatcat aaccctcaaa aagagatggc aactagcact ctccaagggt
    25621 gttcactttg tttgcaactt gctgttgttg tttgtaacag tttactcaca ccttttgctc
    25681 gttgctgctg gccttgaagc cccttttctc tatctttatg ctttagtcta cttcttgcag
    25741 agtataaact ttgtaagaat aataatgagg ctttggcttt gctggaaatg ccgttccaaa
    25801 aacccattac tttatgatgc caactatttt ctttgctggc atactaattg ttacgactat
    25861 tgtatacctt acaatagtgt aacttcttca attgtcatta cttcaggtga tggcacaaca
    25921 agtcctattt ctgaacatga ctaccagatt ggtggttata ctgaaaaatg ggaatctgga
    25981 gtaaaagact gtgttgtatt acacagttac ttcacttcag actattacca gctgtactca
    26041 actcaattga gtacagacac tggtgttgaa catgttacct tcttcatcta caataaaatt
    26101 gttgatgagc ctgaagaaca tgtccaaatt cacacaatcg acggttcatc cggagttgtt
    26161 aatccagtaa tggaaccaat ttatgatgaa ccgacgacga ctactagcgt gcctttgtaa
    26221 gcacaagctg atgagtacga acttatgtac tcattcgttt cggaagagac aggtacgtta
    26281 atagttaata gcgtacttct ttttcttgct ttcgtggtat tcttgctagt tacactagcc
    26341 atccttactg cgcttcgatt gtgtgcgtac tgctgcaata ttgttaacgt gagtcttgta
    26401 aaaccttctt tttacgttta ctctcgtgtt aaaaatctga attcttctag agttcctgat
    26461 cttctggtct aaacgaacta aatattatat tagtttttct gtttggaact ttaattttag
    26521 ccatggcaga ttccaacggt actattaccg ttgaagagct taaaaagctc cttgaacaat
    26581 ggaacctagt aataggtttc ctattcctta catggatttg tcttctacaa tttgcctatg
    26641 ccaacaggaa taggtttttg tatataatta agttaatttt cctctggctg ttatggccag
    26701 taactttagc ttgttttgtg cttgctgctg tttacagaat aaattggatc accggtggaa
    26761 ttgctatcgc aatggcttgt cttgtaggct tgatgtggct cagctacttc attgcttctt
    26821 tcagactgtt tgcgcgtacg cgttccatgt ggtcattcaa tccagaaact aacattcttc
    26881 tcaacgtgcc actccatggc actattctga ccagaccgct tctagaaagt gaactcgtaa
    26941 tcggagctgt gatccttcgt ggacatcttc gtattgctgg acaccatcta ggacgctgtg
    27001 acatcaagga cctgcctaaa gaaatcactg ttgctacatc acgaacgctt tcttattaca
    27061 aattgggagc ttcgcagcgt gtagcaggtg actcaggttt tgctgcatac agtcgctaca
    27121 ggattggcaa ctataaatta aacacagacc attccagtag cagtgacaat attgctttgc
    27181 ttgtacagta agtgacaaca gatgtttcat ctcgttgact ttcaggttac tatagcagag
    27241 atattactaa ttattatgag gacttttaaa gtttccattt ggaatcttga ttacatcata
    27301 aacctcataa ttaaaaattt atctaagtca ctaactgaga ataaatattc tcaattagat
    27361 gaagagcaac caatggagat tgattaaacg aacatgaaaa ttattctttt cttggcactg
    27421 ataacactcg ctacttgtga gctttatcac taccaagagt gtgttagagg tacaacagta
    27481 cttttaaaag aaccttgctc ttctggaaca tacgagggca attcaccatt tcatcctcta
    27541 gctgataaca aatttgcact gacttgcttt agcactcaat ttgcttttgc ttgtcctgac
    27601 ggcgtaaaac acgtctatca gttacgtgcc agatcagttt cacctaaact gttcatcaga
    27661 caagaggaag ttcaagaact ttactctcca atttttctta ttgttgcggc aatagtgttt
    27721 ataacacttt gcttcacact caaaagaaag acagaatgat tgaactttca ttaattgact
    27781 tctatttgtg ctttttagcc tttctgctat tccttgtttt aattatgctt attatctttt
    27841 ggttctcact tgaactgcaa gatcataatg aaacttgtca cgcctaaacg aacatgaaat
    27901 ttcttgtttt cttaggaatc atcacaactg tagctgcatt tcaccaagaa tgtagtttac
    27961 agtcatgtac tcaacatcaa ccatatgtag ttgatgaccc gtgtcctatt cacttctatt
    28021 ctaaatggta tattagagta ggagctagaa aatcagcacc tttaattgaa ttgtgcgtgg
    28081 atgaggctgg ttctaaatca cccattcagt acatcgatat cggtaattat acagtttcct
    28141 gtttaccttt tacaattaat tgccaggaac ctaaattggg tagtcttgta gtgcgttgtt
    28201 cgttctatga agacttttta gagtatcatg acgttcgtgt tgttttagat ttcatctaaa
    28261 cgaacaaact aaaatgtctg ataatggacc ccaaaatcag cgaaatgcac cccgcattac
    28321 gtttggtgga ccctcagatt caactggcag taaccagaat ggagaacgca gtggggcgcg
    28381 atcaaaacaa cgtcggcccc aaggtttacc caataatact gcgtcttggt tcaccgctct
    28441 cactcaacat ggcaaggaag accttaaatt ccctcgagga caaggcgttc caattaacac
    28501 caatagcagt ccagatgacc aaattggcta ctaccgaaga gctaccagac gaattcgtgg
    28561 tggtgacggt aaaatgaaag atctcagtcc aagatggtat ttctactacc taggaactgg
    28621 gccagaagct ggacttccct atggtgctaa caaagacggc atcatatggg ttgcaactga
    28681 gggagccttg aatacaccaa aagatcacat tggcacccgc aatcctgcta acaatgctgc
    28741 aatcgtgcta caacttcctc aaggaacaac attgccaaaa ggcttctacg cagaagggag
    28801 cagaggcggc agtcaagcct cttctcgttc ctcatcacgt agtcgcaaca gttcaagaaa
    28861 ttcaactcca ggcagcagta ggggaacttc tcctgctaga atggctggca atggcggtga
    28921 tgctgctctt gctttgctgc tgcttgacag attgaaccag cttgagagca aaatgtctgg
    28981 taaaggccaa caacaacaag gccaaactgt cactaagaaa tctgctgctg aggcttctaa
    29041 gaagcctcgg caaaaacgta ctgccactaa agcatacaat gtaacacaag ctttcggcag
    29101 acgtggtcca gaacaaaccc aaggaaattt tggggaccag gaactaatca gacaaggaac
    29161 tgattacaaa cattggccgc aaattgcaca atttgccccc agcgcttcag cgttcttcgg
    29221 aatgtcgcgc attggcatgg aagtcacacc ttcgggaacg tggttgacct acacaggtgc
    29281 catcaaattg gatgacaaag atccaaattt caaagatcaa gtcattttgc tgaataagca
    29341 tattgacgca tacaaaacat tcccaccaac agagcctaaa aaggacaaaa agaagaaggc
    29401 tgatgaaact caagccttac cgcagagaca gaagaaacag caaactgtga ctcttcttcc
    29461 tgctgcagat ttggatgatt tctccaaaca attgcaacaa tccatgagca gtgctgactc
    29521 aactcaggcc taaactcatg cagaccacac aaggcagatg ggctatataa acgttttcgc
    29581 ttttccgttt acgatatata gtctactctt gtgcagaatg aattctcgta actacatagc
    29641 acaagtagat gtagttaact ttaatctcac atagcaatct ttaatcagtg tgtaacatta
    29701 gggaggactt gaaagagcca ccacattttc accgaggcca cgcggagtac gatcgagtgt
    29761 acagtgaaca atgctaggga gagctgccta tatggaagag ccctaatgtg taaaattaat
    29821 tttagtagtg ctatccccat gtgattttaa tagcttctta ggagaatgac aaaaaaaaaa
    29881 aaaaaaaaaa aaaaaaaaaa aaa")
h5n1 = clean_sequence("        1 agcaaaagca gggtagataa tcactcaatg agtgacatcg aagccatggc atctcaaggc
       61 accaaacgat catatgaaca aatggagact ggtggggaac gccaggatgc cacagaaatc
      121 agagcatctg tcggaaaaat gattggtgga atcgggaaat tctacatcca aatgtgcact
      181 gaactcaaac tcagtgacta tgagggacga ctaatccaaa atagcataac aatagagaga
      241 atggtgctct ctgcttttga tgagagaaga aataaatacc tagaagagca tcccagtgct
      301 gggaaggatc ctaagaaaac tggaggaccc atatatagaa gagtagacgg aaagtggatg
      361 agagaactca ttctttatga caaagaagaa ataaggagag tttggcgcca agcaaataat
      421 ggtgaagatg caacagctgg tcttactcat atcatgattt ggcattccaa tctgaatgat
      481 gccacgtacc agagaacaag agcgcttgtt cgcaccggaa tggatcccag aatgtgctct
      541 ctaatgcaag gttcaacact tcccagaagg tctggggccg caggtgctgc agtgaaagga
      601 gttggaacaa tagcaatgga attgatcaga atgatcaaac gtgggatcaa tgaccgaaac
      661 ttctggagag gtgaaaatgg acgaaggaca agggttgcat atgaaagaat gtgcaatatt
      721 ctcaaaggaa aatttcagac agctgcccag agggcaatga tggatcaagt gagagaaagt
      781 cggaacccag gaaacgctga gattgaagat ctcattttcc tggcacggtc agcacttatt
      841 ctaaggggat cagttgcaca taagtcttgc ctgcctgctt gtgtgtatgg gcttgcagtg
      901 gcaagtgggc atgactttga aagggaaggg tattcactgg tcgggataga cccgtttaaa
      961 ttactccaaa acagtcaagt gttcagcctg ataagaccaa atgaaaaccc agctcacaag
     1021 agtcaattag tgtggatggc atgccactct gctgcatttg aggatctaag ggtatcaagt
     1081 ttcataagag ggaagaaagt gattccaaga ggaaagcttt ccacaagagg agttcagatt
     1141 gcttcaaatg agaatgtgga agccatggat tccaatacct tagagctgag aagcagatac
     1201 tgggccataa ggaccagaag tggaggaaat accaatcaac aaaaagcatc cgctggccag
     1261 atcagtgtgc aacctacatt ctcagtgcaa cggaatctcc cttttgaaag agcaaccgtt
     1321 atggcagcct tcagcgggaa caatgaagga cggacatccg atatgcgaac agaagttata
     1381 aagatgatgg aaagtgcaaa gccagaagat ttgtccttcc aggggcgggg agtcttcgag
     1441 ctctcggacg aaaaggcaac gagcccgatc gtgccttcct ttgacatgag taatgaagga
     1501 tcttatttct tcggagacaa tgcagaggag tatgacagtt gaggaaaaat acccttgttt
     1561 ctact")
covid_delta = clean_sequence("        1 caaaccaacc aactttcgat ctcttgtaga tctgttctct aaacgaactt taaaatctgt
       61 gtggctgtca ctcggctgca tgcttagtgc actcacgcag tataattaat aactaattac
      121 tgtcgttgac aggacacgag taactcgtct atcttctgca ggctgcttac ggtttcgtcc
      181 gttttgcagc cgatcatcag cacatctagg ttttgtccgg gtgtgaccga aaggtaagat
      241 ggagagcctt gtccctggtt tcaacgagaa aacacacgtc caactcagtt tgcctgtttt
      301 acaggttcgc gacgtgctcg tacgtggctt tggagactcc gtggaggagg tcttatcaga
      361 ggcacgtcaa catcttaaag atggcacttg tggcttagta gaagttgaaa aaggcgtttt
      421 gcctcaactt gaacagccct atgtgttcat caaacgttcg gatgctcgaa ctgcacctca
      481 tggtcatgtt atggttgagc tggtagcaga actcgaaggc attcagtacg gtcgtagtgg
      541 tgagacactt ggtgtccttg tccctcatgt gggcgaaata ccagtggctt accgcaaggt
      601 tcttcttcgt aagaacggta ataaaggagc tggtggccat agttacggcg ccgatctaaa
      661 gtcatttgac ttaggcgacg agcttggcac tgatccttat gaagattttc aagaaaactg
      721 gaacactaaa catagcagtg gtgttacccg tgaactcatg cgtgagctta acggaggggc
      781 atacactcgc tatgtcgata acaacttctg tggccctgat ggctaccctc ttgagtgcat
      841 taaagacctt ctagcacgtg ctggtaaagc ttcatgcact ttgtccgaac aactggactt
      901 tattgacact aagaggggtg tatactgctg ccgtgaacat gagcatgaaa ttgcttggta
      961 cacggaacgt tctgaaaaga gctatgaatt gcagacacct tttgaaatta aattggcaaa
     1021 gaaatttgac accttcaatg gggaatgtcc aaattttgta tttcccttaa attccataat
     1081 caagactatt caaccaaggg ttgaaaagaa aaagcttgat ggctttatgg gtagaattcg
     1141 atctgtctat ccagttgcgt caccaaatga atgcaaccaa atgtgccttt caactctcat
     1201 gaagtgtgat cattgtggtg aaacttcatg gcagacgggc gattttgtta aagccacttg
     1261 cgaattttgt ggcactgaga atttgactaa agaaggtgcc actacttgtg gttacttacc
     1321 ccaaaatgct gttgttaaaa tttattgtcc agcatgtcac aattcagaag taggacctga
     1381 gcatagtctt gccgaatacc ataatgaatc tggcttgaaa accattcttc gtaagggtgg
     1441 tcgcactatt gcctttggag gctgtgtgtt ctcttatgtt ggttgccata acaagtgtgc
     1501 ctattgggtt ccacgtgcta gcgctaacat aggttgtaac catacaggtg ttgttggaga
     1561 aggttccgaa ggtcttaatg acaaccttct tgaaatactc caaaaagaga aagtcaacat
     1621 caatattgtt ggtgacttta aacttaatga agagatcgcc attattttgg catctttttc
     1681 tgcttccaca agtgcttttg tggaaactgt gaaaggtttg gattataaag cattcaaaca
     1741 aattgttgaa tcctgtggta attttaaagt tacaaaagga aaagctaaaa aaggtgcctg
     1801 gaatattggt gaacagaaat caatactgag tcctctttat gcatttgcat cagaggctgc
     1861 tcgtgttgta cgatcaattt tctcccgcac tcttgaaact gctcaaaatt ctgtgcgtgt
     1921 tttacagaag gccgctataa caatactaga tggaatttca cagtattcac tgagactcat
     1981 tgatgctatg atgttcacat ctgatttggc tactaacaat ctagttgtaa tggcctacat
     2041 tacaggtggt gttgttcagt tgacttcgca gtggctaact aacatctttg gcactgttta
     2101 tgaaaaactc aaacccgtcc ttgattggct tgaagagaag tttaaggaag gtgtagagtt
     2161 tcttagagac ggttgggaaa ttgttaaatt tatctcaacc tgtgcttgtg aaattgtcgg
     2221 tggacaaatt gtcacctgtg caaaggaaat taaggagagt gttcagacat tctttaagct
     2281 tgtaaataaa tttttggctt tgtgtgctga ctctatcatt attggtggag ctaaacttaa
     2341 agccttgaat ttaggtgaaa catttgtcac gcactcaaag ggattgtaca gaaagtgtgt
     2401 taaatccaga gaagaaactg gcctactcat gcctctaaaa gccccaaaag aaattatctt
     2461 cttagaggga gaaacacttc ccacagaagt gttaacagag gaagttgtct tgaaaactgg
     2521 tgatttacaa ccattagaac aacctactag tgaagctgtt gaagctccat tggttggtac
     2581 accagtttgt attaacgggc ttatgttgct cgaaatcaaa gacacagaaa agtactgtgc
     2641 ccttgcacct aatatgatgg taacaaacaa taccttcaca ctcaaaggcg gtgcaccaac
     2701 aaaggttact tttggtgatg acactgtgat agaagtgcaa ggttacaaga gtgtgaatat
     2761 cacttttgaa cttgatgaaa ggattgataa agtacttaat gagaagtgct ctgcctatac
     2821 agttgaactc ggtacagaag taaatgagtt cgcctgtgtt gtggcagatg ctgtcataaa
     2881 aactttgcaa ccagtatctg aattacttac accactgggc attgatttag atgagtggag
     2941 tatggctaca tactacttat ttgatgagtc tggtgagttt aaattggctt cacatatgta
     3001 ttgttctttt taccctccag atgaggatga agaagaaggt gattgtgaag aagaagagtt
     3061 tgagccatca actcaatatg agtatggtac tgaagatgat taccaaggta aacctttgga
     3121 atttggtgcc acttctgctg ctcttcaacc tgaagaagag caagaagaag attggttaga
     3181 tgatgatagt caacaaactg ttggtcaaca agacggcagt gaggacaatc agacaactac
     3241 tattcaaaca attgttgagg ttcaacctca attagagatg gaacttacac cagttgttca
     3301 gactattgaa gtgaatagtt ttagtggtta tttaaaactt actgacaatg tatacattaa
     3361 aaatgcagac attgtggaag aagctaaaaa ggtaaaacca acagtggttg ttaatgcagc
     3421 caatgtttac cttaaacatg gaggaggtgt tgcaggagcc ttaaataagg ctactaacaa
     3481 tgccatgcaa gttgaatctg atgattacat agctactaat ggaccactta aagtgggtgg
     3541 tagttgtgtt ttaagcggac acaatcttgc taaacactgt cttcatgttg tcggcccaaa
     3601 tgttaacaaa ggtgaagaca ttcaacttct taagagtgct tatgaaaatt ttaatcagca
     3661 cgaagttcta cttgcaccat tattatcagc tggtattttt ggtgctgacc ctatacattc
     3721 tttaagagtt tgtgtagata ctgttcgcac aaatgtctac ttagctgtct ttgataaaaa
     3781 tctctatgac aaacttgttt caagcttttt ggaaatgaag agtgaaaagc aagttgaaca
     3841 aaagatcgct gagattccta aagaggaagt taagccattt ataactgaaa gtaaaccttc
     3901 agttgaacag agaaaacaag atgataagaa aatcaaagct tgtgttgaag aagttacaac
     3961 aactctggaa gaaactaagt tcctcacaga aaacttgtta ctttatattg acattaatgg
     4021 caatcttcat ccagattctg ccactcttgt tagtgacatt gacatcactt tcttaaagaa
     4081 agatgctcca tatatagtgg gtgatgttgt tcaagagggt gttttaactg ctgtggttat
     4141 acctactaaa aagtctggtg gcactactga aatgctagcg aaagctttga gaaaagtgcc
     4201 aacagacaat tatataacca cttacccggg tcagggttta aatggttaca ctgtagagga
     4261 ggcaaagaca gtgcttaaaa agtgtaaaag tgccttttac attctaccat ctattatctc
     4321 taatgagaag caagaaattc ttggaactgt ttcttggaat ttgcgagaaa tgcttgcaca
     4381 tgcagaagaa acacgcaaat taatgcctgt ctgtgtggaa actaaagcca tagtttcaac
     4441 tatacagcgt aaatataagg gtattaaaat acaagagggt gtggttgatt atggtgctag
     4501 attttacttt tacaccagta aaacaactgt agcgtcactt atcaacacac ttaacgatct
     4561 aaatgaaact cttgttacaa tgccacttgg ctatgtaaca catggcttaa atttggaaga
     4621 agctgctcgg tatatgagat ctctcaaagt gccagctaca gtttctgttt cttcacctga
     4681 tgctgttaca gcgtataatg gttatcttac ttcttcttct aaaacacctg aagaacattt
     4741 tattgaaacc atctcacttg ctggttccta taaagattgg tcctattctg gacaatctac
     4801 acaactaggt atagaatttc ttaagagagg tgataaaagt gtatattaca ctagtaatcc
     4861 taccacattc cacctagatg gtgaagttat cacctttgac aatcttaaga cacttctttc
     4921 tttgagagaa gtgaggacta ttaaggtgtt tacaacagta gacaacatta acctccacac
     4981 gcaagttgtg gacatgtcaa tgacatatgg acaacagttt ggtccaactt atttggatgg
     5041 agctgatgtt actaaaataa aacctcataa ttcacatgaa ggtaaaacat tttatgtttt
     5101 acctaatgat gacactctac gtgttgaggc ttttgagtac taccacacaa ctgatcctag
     5161 ttttctgggt aggtacatgt cagcattaaa tcacactaaa aagtggaaat atccacaagt
     5221 taatggttta acttctatta aatgggcaga taacaactgt tatcttgcca ctgcattgtt
     5281 aacactccaa caaatagagt tgaagtttaa tccacctgct ctacaagatg cttattacag
     5341 agcaagggct ggtgaagctg ctaacttttg tgcacttatc ttagcctact gtaataagac
     5401 agtaggtgag ttaggtgatg ttagagaaac aatgagttac ttgtttcaac atgccaattt
     5461 agattcttgc aaaagagtct tgaacgcggt gtgtaaaact tgtggacaac agcagacaac
     5521 ccttaagggt gtagaagctg ttatgtacat gggcacactt tcttatgaac aatttaagaa
     5581 aggtgttcag ataccttgta cgtgtggtaa acaagctaca aaatatctag tacaacagga
     5641 gtcacctttt gttatgatgt cagcaccacc tgctcagtat gaacttaagc atggtacatt
     5701 tacttgtgct agtgagtaca ctggtaatta ccagtgtggt cactataaac atataacttc
     5761 taaagaaact ttgtattgca tagacggtgc tttacttaca aagtcctcag aatacaaagg
     5821 tcctattacg gatgttttct acaaagaaaa cagttacaca acaaccataa aaccagttac
     5881 ttataaattg gatggtgttg tttgtacaga aattgaccct aagttggaca attattataa
     5941 gaaagacaat tcttatttca cagagcaacc aattgatctt gtaccaaacc aaccatatcc
     6001 aaacgcaagc ttcgataatt ttaagtttgt atgtgataat atcaaatttg ctgatgattt
     6061 aaaccagtta actggttata agaaacctgc ttcaagagag cttaaagtta catttttccc
     6121 tgacttaaat ggtgatgtgg tggctattga ttataaacac tacacaccct cttttaagaa
     6181 aggagctaaa ttgttacata aacctattgt ttggcatgtt aacaatgcaa ctaataaagc
     6241 cacgtataaa ccaaatacct ggtgtatacg ttgtctttgg annnnnnnnn nnnnnnnnnn
     6301 nnnnnnnnnn nnnnatgtac tgaagtcaga ggacgcgcag ggaatggata atcttgcctg
     6361 cgaagatcta aaactagtct ctgaagaagt agtggaaaat cctaccatac agaaagacgt
     6421 tcttgagtgt aatgtgaaaa ctaccgaagt tgtaggagac attatactta aaccagcaaa
     6481 taatagttta aaaattacag aagaggttgg ccacacagat ctaatggctg cttatgtaga
     6541 caattctagt cttactatta agaaacctaa tgaattatct agagtattag gtttgaaaac
     6601 ccttgctact catggtttag ctgctgttaa tagtgtccct tgggatacta tagctaatta
     6661 tgctaagcct tttcttaaca aagttgttag tacaactact aacatagtta cacggtgttt
     6721 aaaccgtgtt tgtactaatt atatgcctta tttctttact ttattgctac aattgtgtac
     6781 ttttactaga agtacaaatt ctagaattaa agcatctatg ccgactacta tagcaaagaa
     6841 tactgttaag agtgtcggta aattttgtct agaggcttca tttaattatt tgaagtcacc
     6901 taatttttct aaactgataa atattataat ttggttttta ctattaagtg tttgcctagg
     6961 ttctttaatc tactcaaccg ctgctttagg tgttttaatg tctaatttag gcatgccttc
     7021 ttactgtact ggttacagag aaggctattt gaactctact aatgtcacta ttgcaaccta
     7081 ctgtactggt tctatatctt gtagtgtttg tcttagtggt ttagattctt tagacaccta
     7141 tccttcttta gaaactatac aaattaccat ttcatctttt aaatgggatt taactgcttt
     7201 tggcttagtt gcagagtggt ttttggcata tattcttttc actaggtttt tctatgtact
     7261 tggattggct gcaatcatgc aattgttttt cagctatttt gcagtacatt ttattagtaa
     7321 ttcttggctt atgtggttaa taattaatct tgtacaaatg gccccgattt cagctatggt
     7381 tagaatgtac atcttctttg catcatttta ttatgtatgg aaaagttatg tgcatgttgt
     7441 agacggttgt aattcatcaa cttgtatgat gtgttacaaa cgtaatagag caacaagagt
     7501 cgaatgtaca actattgtta atggtgttag aaggtccttt tatgtctatg ctaatggagg
     7561 taaaggcttt tgcaaactac acaattggaa ttgtgttaat tgtgatacat tctgtgctgg
     7621 tagtacattt attagtgatg aagttgcgag agacttgtca ctacagttta aaagaccaat
     7681 aaatcctact gaccagtctt cttacatcgt tgatagtgtt acagtgaaga atggttccat
     7741 ccatctttac tttgataaag ctggtcaaaa gacttatgaa agacattctc tctctcattt
     7801 tgttaactta gacaacctga gagctaataa cactaaaggt tcattgccta ttaatgttat
     7861 agtttttgat ggtaaatcaa aatgtgaaga atcatctgca aaatcagcgt ctgtttacta
     7921 cagtcagctt atgtgtcaac ctatactgtt actagatcag gcattagtgt ctgatgttgg
     7981 tgatagtgcg gaagttgcag ttaaaatgtt tgatgcttac gttaatacgt tttcatcaac
     8041 ttttaacgta ccaatggaaa aactcaaaac actagttgca actgcagaag ctgaacttgc
     8101 aaagaatgtg tccttagaca atgtcttatc tacttttatt tcagcagctc ggcaagggtt
     8161 tgttgattca gatgtagaaa ctaaagatgt tgttgaatgt cttaaattgt cacatcaatc
     8221 tgacatagaa gttactggcg atagttgtaa taactatatg ctcacctata acaaagttga
     8281 aaacatgaca ccccgtgacc ttggtgcttg tattgactgt agtgcgcgtc atattaatgc
     8341 gcaggtagca aaaagtcaca acattgcttt gatatggaac gttaaagatt tcatgtcatt
     8401 gtctgaacaa ctacgaaaac aaatacgtag tgctgctaaa aagaataact taccttttaa
     8461 gttgacatgt gcaactacta gacaagttgt taatgttgta acaacaaaga tagcacttaa
     8521 gggtggtaaa attgttaata attggttgaa gcagttaatt aaagttacac ttgtgttcct
     8581 ttttgttgct gctattttct atttaataac acctgttcat gtcatgtcta aacatactga
     8641 cttttcaagt gaaatcatag gatacaaggc tattgatggt ggtgtcactc gtgacatagc
     8701 atctacagat acttgttttg ctaacaaaca tgctgatttt gacacatggt ttagccagcg
     8761 tggtggtagt tatactaatg acaaagcttg cccattgatt gctgcagtca taacaagaga
     8821 agtgggtttt gtcgtgcctg gtttgcctgg cacgatatta cgcacaacta atggtgactt
     8881 tttgcatttc ttacctagag tttttagtgc agttggtaac atctgttaca caccatcaaa
     8941 acttatagag tacactgatt ttgcaacatc agcttgtgtt ttggctgctg aatgtacaat
     9001 ttttaaagat gcttctggta agccattacc atattgttat gataccaatg tactagaagg
     9061 ttctgttgct tatgaaagtt tacgccctga cacacgttat gtgctcatgg atggctctat
     9121 tattcaattt cctaacacct accttgaagg ttctgttaga gtggtaacaa cttttgattc
     9181 tgagtactgt aggcacggca cttgtgaaag atcagaagct ggtgtttgtg tatctactag
     9241 tggtagatgg gtacttaaca atgattatta cagatcttta ccaggagttt tctgtggtgt
     9301 agatgctgta aatttactta ctaatatgtt tacaccacta attcaaccta ttggtgcttt
     9361 ggacatatca gcatctatag tagctggtgg tattgtagct atcgtagtaa catgccttgc
     9421 ctactatttt atgaggttta gaagagcttt tggtgaatac agtcatgtag ttgcctttaa
     9481 tactttacta ttccttatgt cattcactgt actctgttta acaccagttt actcattctt
     9541 acctggtgtt tattctgtta tttacttgta cttgacattt tatcttacta atgatgtttc
     9601 ttttttagca catattcagt ggatggttat gttcacacct ttagtacctt tctggataac
     9661 aattgcttat atcatttgta tttccacaaa gcatttctat tggttcttta gtaattacct
     9721 aaagagacgt gtagtcttta atggtgtttc ctttagtact tttgaagaag ctgcgctgtg
     9781 cacctttttg ttaaataaag aaatgtatct aaagttgcgt agtgatgtgc tattacctct
     9841 tacgcaatat aatagatact tagctcttta taataagtac aagtatttta gtggagcaat
     9901 ggatacaact agctacagag aagctgcttg ttgtcatctc gcaaaggctc tcaatgactt
     9961 cagtaactca ggttctgatg ttctttacca accaccacaa atctctatca cctcagctgt
    10021 tttgcagagt ggttttagaa aaatggcatt cccatctggt aaagttgagg gttgtatggt
    10081 acaagtaact tgtggtacaa ctacacttaa cggtctttgg cttgatgacg tagtttactg
    10141 tccaagacat gtgatctgca cctctgaaga catgcttaac cctaattatg aagatttact
    10201 cattcgtaag tctaatcata atttcttggt acaggctggt aatgttcaac tcagggttat
    10261 tggacattct atgcaaaatt gtgtacttaa gcttaaggtt gatacagcca atcctaagac
    10321 acctaagtat aagtttgttc gcattcaacc aggacagact ttttcagtgt tagcttgtta
    10381 caatggttca ccatctggtg tttaccaatg tgctatgagg cccaatttca ctattaaggg
    10441 ttcattcctt aatggttcat gtggtagtgt tggttttaac atagattatg actgtgtctc
    10501 tttttgttac atgcaccata tggaattacc aactggagtt catgctggca cagacttaga
    10561 aggtaacttt tatggacctt ttgttgacag gcaaacagca caagcagctg gtacggacac
    10621 aactattaca gttaatgttt tagcttggtt gtacgctgct gttataaatg gagacaggtg
    10681 gtttctcaat cgatttacca caactcttaa tgactttaac cttgtggcta tgaagtacaa
    10741 ttatgaacct ctaacacaag accatgttga catactagga cctctttctg ctcaaactgg
    10801 aattgccgtt ttagatatgt gtgcttcatt aaaagaatta ctgcaaaatg gtatgaatgg
    10861 acgtaccata ttgggtagtg ctttattaga agatgaattt acaccttttg atgttgttag
    10921 acaatgctca ggtgttactt tccaaagtgc agtgaaaaga acaatcaagg gtacacacca
    10981 ctggttgtta ctcacaattt tgacttcact tttagtttta gtccagagta ctcaatggtc
    11041 tttgttcttt tttttgtatg aaaatgcctt tttacctttt gctatgggta ttattgctat
    11101 gtctgctttt gcaatgatgt ttgtcaaaca taagcatgca tttctctgtt tgtttttgtt
    11161 accttctctt gccgctgtag cttattttaa tatggtctat atgcctgcta gttgggtgat
    11221 gcgtattatg acatggttgg atatggttga tactagtttg tctggtttta agctaaaaga
    11281 ctgtgttatg tatgcatcag ctgtggtgtt actaatcctt atgacagcaa gaactgtgta
    11341 tgatgatggt gctaggagag tgtggacact tatgaatgtc ttgacactcg tttataaagt
    11401 ttattatggt aatgctttag atcaagccat ttccatgtgg gctcttataa tctctgttac
    11461 ttctaactac tcaggtgtag ttacaactgt catgtttttg gccagaggta ttgtttttat
    11521 gtgtgttgag tattgcccta ttttcttcat aactggtaat acacttcagt gtataatgct
    11581 agtttattgt ttcttaggct atttttgtac ttgttacttt ggcctctttt gtttactcaa
    11641 ccgctacttt agactgactc ttggtgttta tgattactta gtttctacac aggagtttag
    11701 atatatgaat tcacagggac tactcccacc caagaatagc atagatgcct tcaaactcaa
    11761 cattaaattg ttgggtgttg gtggcaaacc ttgtatcaaa gtagccactg tacagtctaa
    11821 aatgtcagat gtaaagtgca catcagtagt cttactctca gttttgcaac aactcagagt
    11881 agaatcatca tctaaattgt gggctcaatg tgtccagtta cacaatgaca ttctcttagc
    11941 taaagatact actgaagcct ttgaaaaaat ggtttcacta ctttctgttt tgctttccat
    12001 gcagggtgct gtagacataa acaagctttg tgaagaaatg ctggacaaca gggcaacctt
    12061 acaagctata gcctcagagt ttagttccct tccatcatat gcagcttttg ctactgctca
    12121 agaagcttat gagcaggctg ttgctaatgg tgattctgaa gttgttctta aaaagttgaa
    12181 gaagtctttg aatgtggcta aatctgaatt tgaccgtgat gcagccatgc aacgtaagtt
    12241 ggaaaagatg gctgatcaag ctatgaccca aatgtataaa caggctagat ctgaggacaa
    12301 gagggcaaaa gttactagtg ctatgcagac aatgcttttc actatgctta gaaagttgga
    12361 taatgatgca ctcaacaaca ttatcaacaa tgcaagagat ggttgtgttc ccttgaacat
    12421 aatacctctt acaacagcag ccaaactaat ggttgtcata ccagactata acacatataa
    12481 aaatacgtgt gatggtacaa catttactta tgcatcagca ttgtgggaaa tccaacaggt
    12541 tgtagatgca gatagtaaaa ttgttcaact tagtgaaatt agtatggaca attcacctaa
    12601 tttagcatgg cctcttattg taacagcttt aagggccaat tctgctgtca aattacagaa
    12661 taatgagctt agtcctgttg cactacgaca gatgtcttgt gctgccggta ctacacaaac
    12721 tgcttgcact gatgacaatg cgttagctta ctacaacaca acaaagggag gtaggtttgt
    12781 acttgcactg ttatccgatt tacaggattt gaaatgggct agattcccta agagtgatgg
    12841 aactggtact atctatacag aactggaacc accttgtagg tttgttacag acacacctaa
    12901 aggtcctaaa gtgaagtatt tatactttat taaaggatta aacaacctaa atagaggtat
    12961 ggtacttggt agtttagctg ccacagtacg tctacaagct ggtaatgcaa cagaagtgcc
    13021 tgccaattca actgtattat ctttctgtgc ttttgctgta gatgctgcta aagcttacaa
    13081 agattatcta gctagtgggg gacaaccaat cactaattgt gttaagatgt tgtgtacaca
    13141 cactggtact ggtcaggcaa taacagttac accggaagcc aatatggatc aagaatcctt
    13201 tggtggtgca tcgtgttgtc tgtactgccg ttgccacata gatcatccaa atcctaaagg
    13261 attttgtgac ttaaaaggta agtatgtaca aatacctaca acttgtgcta atgaccctgt
    13321 gggttttaca cttaaaaaca cagtctgtac cgtctgcggt atgtggaaag gttatggctg
    13381 tagttgtgat caactccgcg aacccatgct tcagtcagct gatgcacaat cgtttttaaa
    13441 cgggtttgcg gtgtaagtgc agcccgtctt acaccgtgcg gcacaggcac tagtactgat
    13501 gtcgtataca gggcttttga catctacaat gataaagtag ctggttttgc taaattccta
    13561 aaaactaatt gttgtcgctt ccaagaaaag gacgaagatg acaatttaat tgattcttac
    13621 tttgtagtta agagacacac tttctctaac taccaacatg aagaaacaat ttataattta
    13681 cttaaggatt gtccagctgt tgctaaacat gacttcttta agtttagaat agacggtgac
    13741 atggtaccac atatatcacg tcaacgtctt actaaataca caatggcaga cctcgtctat
    13801 gctttaaggc attttgatga aggtaattgt gacacattaa aagaaatact tgtcacatac
    13861 aattgttgtg atgatgatta tttcaataaa aaggactggt atgattttgt agaaaaccca
    13921 gatatattac gcgtatacgc caacttaggt gaacgtgtac gccaagcttt gttaaaaaca
    13981 gtacaattct gtgatgccat gcgaaatgct ggtattgttg gtgtactgac attagataat
    14041 caagatctca atggtaactg gtatgatttc ggtgatttca tacaaaccac gccaggtagt
    14101 ggagttcctg ttgtagattc ttattattca ttgttaatgc ctatattaac cttgaccagg
    14161 gctttaactg cagagtcaca tgttgacact gacttaacaa agccttacat taagtgggat
    14221 ttgttaaaat atgacttcac ggaagagagg ttaaaactct ttgaccgtta ttttaaatat
    14281 tgggatcaga cataccaccc aaattgtgtt aactgtttgg atgacagatg cattctgcat
    14341 tgtgcaaact ttaatgtttt attctctaca gtgttcccac ttacaagttt tggaccacta
    14401 gtgagaaaaa tatttgttga tggtgttcca tttgtagttt caactggata ccacttcaga
    14461 gagctaggtg ttgtacataa tcaggatgta aacttacata gctctagact tagttttaag
    14521 gaattacttg tgtatgctgc tgaccctgct atgcacgctg cttctggtaa tctattacta
    14581 gataaacgca ctacgtgctt ttcagtagct gcacttacta acaatgttgc ttttcaaact
    14641 gtcaaacccg gtaattttaa caaagacttc tatgactttg ctgtgtctaa gggtttcttt
    14701 aaggaaggaa gttctgttga attaaaacac ttcttctttg ctcaggatgg taatgctgct
    14761 atcagcgatt atgactacta tcgttataat ctaccaacaa tgtgtgatat cagacaacta
    14821 ctatttgtag ttgaagttgt tgataagtac tttgattgtt acgatggtgg ctgtattaat
    14881 gctaaccaag tcatcgtcaa caacctagac aaatcagctg gttttccatt taataaatgg
    14941 ggtaaggcta gactttatta tgattcaatg agttatgagg atcaagatgc acttttcgca
    15001 tatacaaaac gtaatgtcat ccctactata actcaaatga atcttaagta tgccattagt
    15061 gcaaagaata gagctcgcac cgtagctggt gtctctatct gtagtactat gaccaataga
    15121 cagtttcatc aaaaattatt gaaatcaata gccgccacta gaggagctac tgtagtaatt
    15181 ggaacaagca aattctatgg tggttggcac aacatgttaa aaactgttta tagtgatgta
    15241 gaaaaccctc accttatggg ttgggattat cctaaatgtg atagagccat gcctaacatg
    15301 cttagaatta tggcctcact tgttcttgct cgcaaacata caacgtgttg tagcttgtca
    15361 caccgtttct atagattagc taatgagtgt gctcaagtat tgagtgaaat ggtcatgtgt
    15421 ggcagttcac tatatgttaa accaggtgga acctcatcag gagatgccac aactgcttat
    15481 gctaatagtg tttttaacat ttgtcaagct gtcacggcca atgttaatgc acttttatct
    15541 actgatggta acaaaattgc cgataagtat gtccgcaatt tacaacacag actttatgag
    15601 tgtctctata gaaatagaga tgttgacaca gactttgtga atgagtttta cgcatatttg
    15661 cgtaaacatt tctcaatgat gatactctct gacgatgctg ttgtgtgttt caatagcact
    15721 tatgcatctc aaggtctagt ggctagcata aagaacttta agtcagttct ttattatcaa
    15781 aacaatgttt ttatgtctga agcaaaatgt tggactgaga ctgaccttac taaaggacct
    15841 catgaatttt gctctcaaca tacaatgcta gttaaacagg gtgatgatta tgtgtacctt
    15901 ccttacccag atccatcaag aatcctaggg gccggctgtt ttgtagatga tatcgtaaaa
    15961 acagatggta cacttatgat tgaacggttc gtgtctttag ctatagatgc ttacccactt
    16021 actaaacatc ctaatcagga gtatgctgat gtctttcatt tgtacttaca atacataaga
    16081 aagctacatg atgagttaac aggacacatg ttagacatgt attctgttat gcttactaat
    16141 gataacactt caaggtattg ggaacctgag ttttatgagg ctatgtacac accgcataca
    16201 gtcttacagg ctgttggggc ttgtgttctt tgcaattcac agacttcatt aagatgtggt
    16261 gcttgcatac gtagaccatt cttatgttgt aaatgctgtt acgaccatgt catatcaaca
    16321 tcacataaat tagtcttgtc tgttaatccg tatgtttgca atgctccagg ttgtgatgtc
    16381 acagatgtga ctcaacttta cttaggaggt atgagctatt attgtaaatc acataaacta
    16441 cccattagtt ttccattgtg tgctaatgga caagtttttg gtttatataa aaatacatgt
    16501 gttggtagcg ataatgttac tgactttaat gcaattgcaa catgtgactg gacaaatgct
    16561 ggtgattaca ttttagctaa cacctgtact gaaagactca agctttttgc agcagaaacg
    16621 ctcaaagcta ctgaggagac atttaaactg tcttatggta ttgctactgt acgtgaagtg
    16681 ctgtctgaca gagaattaca tctttcatgg gaagttggta aacctagacc accacttaac
    16741 cgaaattatg tctttactgg ttatcgtgta actaaaaaca gtaaagtaca aataggagag
    16801 tacacctttg aaaaaggtga ctatggtgat gctgttgttt accgaggtac aacaacttac
    16861 aaattaaatg ttggtgatta ttttgtgctg acatcacata cagtaatgcc attaagtgca
    16921 cctacactag tgccacaaga gcactatgtt agaattactg gcttataccc aacactcaat
    16981 atctcagatg agttttctag caatgttgca aattatcaaa aggttggtat gcaaaagtat
    17041 tctacactcc agggaccacc tggtactggt aagagtcatt ttgctattgg cctagctctc
    17101 tactaccctt ctgctcgcat agtgtataca gcttgctctc atgccgctgt tgatgcacta
    17161 tgtgagaagg cattaaaata tttgcctata gataaatgta gtagaattat acctgcacgt
    17221 gctcgtgtag agtgttttga taaattcaaa gtgaattcaa cattagaaca gtatgtcttt
    17281 tgtactgtaa atgcattgcc tgagacgaca gcagatatag ttgtctttga tgaaatttca
    17341 atggccacaa attatgattt gagtgttgtc aatgccagat tacgtgctaa gcactatgtg
    17401 tacattggcg accctgctca attacctgca ccacgcacat tgctaactaa gggcacacta
    17461 gaaccagaat atttcaattc agtgtgtaga cttatgaaaa ctataggtcc agacatgttc
    17521 ctcggaactt gtcggcgttg tcctgctgaa attgttgaca ctgtgagtgc tttggtttat
    17581 gataataagc ttaaagcaca taaagacaaa tcagctcaat gctttaaaat gttttataag
    17641 ggtgttatca cgcatgatgt ttcatctgca attaacaggc cacaaatagg cgtggtaaga
    17701 gaattcctta cacgtaaccc tgcttggaga aaagctgtct ttatttcacc ttataattca
    17761 cagaatgctg tagcctcaaa gattttggga ctaccaactc aaactgttga ttcatcacag
    17821 ggctcagaat atgactatgt catattcact caaaccactg aaacagctca ctcttgtaat
    17881 gtaaacagat ttaatgttgc tattaccaga gcaaaagtag gcatactttg cataatgtct
    17941 gatagagacc tttatgacaa gttgcaattt acaagtcttg aaattccacg taggaatgtg
    18001 gcaactttac aagctgaaaa tgtaacagga ctctttaaag attgtagtaa ggtaatcact
    18061 gggttacatc ctacacaggc acctacacac ctcagtgttg acactaaatt caaaactgaa
    18121 ggtttatgtg ttgacatacc tggcatacct aaggacatga cctatagaag actcatctct
    18181 atgatgggtt ttaaaatgaa ttatcaagtt aatggttacc ctaacatgtt tatcacccgc
    18241 gaagaagcta taagacatgt acgtgcatgg attggcttcg atgtcgaggg gtgtcatgct
    18301 actagagaag ctgttggtac caatttacct ttacagctag gtttttctac aggtgttaac
    18361 ctagttgctg tacctacagg ttatgttgat acacctaata atacagattt ttccagagtt
    18421 agtgctaaac caccgcctgg agatcaattt aaacacctca taccacttat gtacaaagga
    18481 cttccttgga atgtagtgcg tataaagatt gtacaaatgt taagtgacac acttaaaaat
    18541 ctctctgaca gagtcgtatt tgtcttatgg gcacatggct ttgagttgac atctatgaag
    18601 tattttgtga aaataggacc tgagcgcacc tgttgtctat gtgatagacg tgccacatgc
    18661 ttttccactg cttcagacac ttatgcctgt tggcatcatt ctattggatt tgattacgtc
    18721 tataatccgt ttatgattga tgttcaacaa tggggtttta caggtaacct acaaagcaac
    18781 catgatctgt attgtcaagt ccatggtaat gcacatgtag ctagttgtga tgcaatcatg
    18841 actaggtgtc tagctgtcca cgagtgcttt gttaagcgtg ttgactggac tattgaatat
    18901 cctataattg gtgatgaact gaagattaat gcggcttgta gaaaggttca acacatggtt
    18961 gttaaagctg cattattagc agacaaattc ccagttcttc acgacattgg taaccctaaa
    19021 gctattaagt gtgtacctca agctgatgta gaatggaagt tctatgatgc acagccttgt
    19081 agtgacaaag cttataaaat agaagaatta ttctattctt atgccacaca ttctgacaaa
    19141 ttcacagatg gtgtatgcct attttggaat tgcaatgtcg atagatatcc tgttaattcc
    19201 attgtttgta gatttgacac tagagtgcta tctaacctta acttgcctgg ttgtgatggt
    19261 ggcagtttgt atgtaaataa acatgcattc cacacaccag cttttgataa aagtgctttt
    19321 gttaatttaa aacaattacc atttttctat tactctgaca gtccatgtga gtctcatgga
    19381 aaacaagtag tgtcagatat agattatgta ccactaaagt ctgctacgtg tataacacgt
    19441 tgcaatttag gtggtgctgt ctgtagacat catgctaatg agtacagatt gtatctcgat
    19501 gcttataaca tgatgatctc agctggcttt agcttgtggg tttacaaaca atttgatact
    19561 tataacctct ggaacacttt tacaagactt cagagtttag aaaatgtggc ttttaatgtt
    19621 gtaaataagg gacactttga tggacaacag ggtgaagtac cagtttctat cattaataac
    19681 actgtttaca caaaagttga tggtgttgat gtagaattgt ttgaaaataa aacaacatta
    19741 cctgttaatg tagcatttga gctttgggct aagcgcaaca ttaaaccagt accagaggtg
    19801 aaaatactca ataatttggg tgtggacatt gctgctaata ctgtgatctg ggactacaaa
    19861 agagatgctc cagcacatat atctactatt ggtgtttgtt ctatgactga catagccaag
    19921 aaaccaactg aaacgatttg tgcaccactc actgtctttt ttgatggtag agttgatggt
    19981 caagtagact tatttagaaa tgcccgtaat ggtgttctta ttacagaagg tagtgttaaa
    20041 ggtttacaac catctgtagg tcccaaacaa gctagtctta atggagtcac attaattgga
    20101 gaagccgtaa aaacacagtt caattattat aagaaagttg atggtgttgt ccaacaatta
    20161 cctgaaactt actttactca gagtagaaat ttacaagaat ttaaacccag gagtcaaatg
    20221 gaaattgatt tcttagaatt agctatggat gaattcattg aacggtataa attagaaggc
    20281 tatgccttcg aacatatcgt ttatggagat tttagtcata gtcagttagg tggtttacat
    20341 ctactgattg gactagctaa acgttttaag gaatcacctt ttgaattaga agattttatt
    20401 cctatggaca gtacagttaa aaactatttc ataacagatg cgcaaacagg ttcatctaag
    20461 tgtgtgtgtt ctgttattga tttattactt gatgattttg ttgaaataat aaaatcccaa
    20521 gatttatctg tagtttctaa ggttgtcaaa gtgactattg actatacaga aatttcattt
    20581 atgctttggt gtaaagatgg ccatgtagaa acattttacc caaaattaca atctagtcaa
    20641 gcgtggcaac cgggtgttgc tatgcctaat ctttacaaaa tgcaaagaat gctattagaa
    20701 aagtgtgacc ttcaaaatta tggtgatagt gcaacattac ctaaaggcat aatgatgaat
    20761 gtcgcaaaat atactcaact gtgtcaatat ttaaacacat taacattagc tgtaccctat
    20821 aatatgagag ttatacattt tggtgctggt tctgataaag gagttgcacc aggtacagct
    20881 gttttaagac agtggttgcc tacgggtacg ctgcttgtcg attcagatct taatgacttt
    20941 gtctctgatg cagattcaac tttgattggt gattgtgcaa ctgtacatac agctaataaa
    21001 tgggatctca ttattagtga tatgtacgac cctaagacta aaaatgttac aaaagaaaat
    21061 gactctaaag agggtttttt cacttacatt tgtgggttta tacaacaaaa gctagctctt
    21121 ggaggttccg tggctataaa gataacagaa cattcttgga atgctgatct ttataagctc
    21181 atgggacact tcgcatggtg gacagccttt gttactaatg tgaatgcgtc atcatctgaa
    21241 gcatttttaa ttggatgtaa ttatcttggc aaaccacgcg aacaaataga tggttatgtc
    21301 atgcatgcaa attacatatt ttggaggaat acaaatccaa ttcagttgtc ttcctattct
    21361 ttatttgaca tgagtaaatt tccccttaaa ttaaggggta ctgctgttat gtctttaaaa
    21421 gaaggtcaaa tcaatgatat gattttatct cttcttagta aaggtagact tataattaga
    21481 gaaaacaaca gagttgttat ttctagtgat gttcttgtta acaactaaac gaacaatgtt
    21541 tgtttttctt gttttattgc cactagtctc tagtcagtgt gttaatctta gaaccagaac
    21601 tcaattaccc cctgcataca ctaattcttt cacacgtggt gtttattacc ctgacaaagt
    21661 tttcagatcc tcagttttac attcaactca ggacttgttc ttacctttct tttccaatgt
    21721 tacttggttc catgctatac atgtctctgg gaccaatggt actaagaggt ttgataaccc
    21781 tgtcctacca tttaatgatg gtgtttattt tgcttccayt gagaagtcta acataataag
    21841 aggctggatt tttggtacta ctttagattc gaagacccag tccctactta ttgttaataa
    21901 cgctactaat gttgttatta aagtctgtga atttcaattt tgtaatgatc catttttgga
    21961 tgtttattac cacaaaaaca acaaaagttg gatggaaagt gnnnnnngag tttattctag
    22021 tgcgaataat tgcacttttg aatatgtctc tcagcctttt cttatggacc ttgaaggaaa
    22081 acagggtaat ttcaaaaatc ttagggaatt tgtgtttaag aatattgatg gttattttaa
    22141 aatatattct aagcacacgc ctattaattt agtgcgtgat ctccctcagg gtttttcggc
    22201 tttagaacca ttggtagatt tgccaatagg tattaacatc actaggtttc aaactttact
    22261 tgctttacat agaagttatt tgactcctgg tgattcttct tcaggttgga cagctggtgc
    22321 tgcagcttat tatgtgggtt atcttcaacc taggactttt ctattaaaat ataatgaaaa
    22381 tggaaccatt acagatgctg tagactgtgc acttgaccct ctctcagaaa caaagtgtac
    22441 gttgaaatcc ttcactgtag aaaaaggaat ctatcaaact tctaacttta gagtccaacc
    22501 aacagaatct attgttagat ttcctaatat tacaaacttg tgcccttttg gtgaagtttt
    22561 taacgccacc agatttgcat ctgtttatgc ttggaacagg aagagaatca gcaactgtgt
    22621 tgctgattat tctgtcctat ataattccgc atcattttcc acttttaagt gttatggagt
    22681 gtctcctact aaattaaatg atctctgctt tactaatgtc tatgcagatt catttgtaat
    22741 tagaggtgat gaagtcagac aaatcgctcc agggcaaact ggaaagattg ctgattataa
    22801 ttataaatta ccagatgatt ttacaggctg cgttatagct tggaattcta acaatcttga
    22861 ttctaaggtt ggtggtaatt ataattaccg gtatagattg tttaggaagt ctaatctcaa
    22921 accttttgag agagatattt caactgaaat ctatcaggcc ggtagcaaac cttgtaatgg
    22981 tgttgaaggt tttaattgtt actttccttt acaatcatat ggtttccaac ccactaatgg
    23041 tgttggttac caaccataca gagtagtagt actttctttt gaacttctac atgcaccagc
    23101 aactgtttgt ggacctaaaa agtctactaa tttggttaaa aacaaatgtg tcaatttcaa
    23161 cttcaatggt ttaacaggca caggtgttct tactgagtct aacaaaaagt ttctgccttt
    23221 ccaacaattt ggcagagaca ttgctgacac tactgatgct gtccgtgatc cacagacact
    23281 tgagattctt gacattacac catgttcttt tggtggtgtc agtgttataa caccaggaac
    23341 aaatacttct aaccaggttg ctgttcttta tcagggtgtt aactgcacag aagtccctgt
    23401 tgctattcat gcagatcaac ttactcctac ttggcgtgtt tattctacag gttctaatgt
    23461 ttttcaaaca cgtgcaggct gtttaatagg ggctgaacat gtcaacaact catatgagtg
    23521 tgacataccc attggtgcag gtatatgcgc tagttatcag actcagacta attctcgtcg
    23581 gcgggcacgt agtgtagcta gtcaatccat cattgcctac actatgtcac ttggtgcaga
    23641 aaattcagtt gcttactcta ataactctat tgccataccc acaaatttta ctattagtgt
    23701 taccacagaa attctaccag tgtctatgac caagacatca gtagattgta caatgtacat
    23761 ttgtggtgat tcaactgaat gcagcaatct tttgttgcaa tatggcagtt tttgtacaca
    23821 attaaaccgt gctttaactg gaatagctgt tgaacaagac aaaaacaccc aagaagtttt
    23881 tgcacaagtc aaacaaattt acaaaacacc accaattaaa gattttggtg gttttaattt
    23941 ttcacaaata ttaccagatc catcaaaacc aagcaagagg tcatttattg aagatctact
    24001 tttcaacaaa gtgacacttg cagatgctgg cttcatcaaa caatatggtg attgccttgg
    24061 tgatattgct gctagagacc tcatttgtgc acaaaagttt aacggcctta ctgttttgcc
    24121 acctttgctc acagatgaaa tgattgctca atacacttct gcactgttag cgggtacaat
    24181 cacttctggt tggacctttg gtgcaggtgc tgcattacaa ataccatttg ctatgcaaat
    24241 ggcttatagg tttaatggta ttggagttac acagaatgtt ctctatgaga accaaaaatt
    24301 gattgccaac caatttaata gtgctattgg caaaattcaa gactcacttt cttccacagc
    24361 aagtgcactt ggaaaacttc aaaatgtggt caaccaaaat gcacaagctt taaacacgct
    24421 tgttaaacaa cttagctcca attttggtgc aatttcaagt gttttaaatg atatcctttc
    24481 acgtcttgac aaagttgagg ctgaagtgca aattgatagg ttgatcacag gcagacttca
    24541 aagtttgcag acatatgtga ctcaacaatt aattagagct gcagaaatca gagcttctgc
    24601 taatcttgct gctactaaaa tgtcagagtg tgtacttgga caatcaaaaa gagttgattt
    24661 ttgtggaaag ggctatcatc ttatgtcctt ccctcagtca gcacctcatg gtgtagtctt
    24721 cttgcatgtg acttatgtcc ctgcacaaga aaagaacttc acaactgctc ctgccatttg
    24781 tcatgatgga aaagcacact ttcctcgtga aggtgtcttt gtttcaaatg gcacacactg
    24841 gtttgtaaca caaaggaatt tttatgaacc acaaatcatt actacagaca acacatttgt
    24901 gtctggtaac tgtgatgttg taataggaat tgtcaacaac acagtttatg atcctttgca
    24961 acctgaatta gactcattca aggaggagtt agataaatat tttaagaatc atacatcacc
    25021 agatgttgat ttaggtgaca tctctggcat taatgcttca gttgtaaaca ttcaaaaaga
    25081 aattgaccgc ctcaatgagg ttgccaagaa tttaaatgaa tctctcatcg atctccaaga
    25141 acttggaaag tatgagcagt atataaaatg gccatggtac atttggctag gttttatagc
    25201 tggcttgatt gccatagtaa tggtgacaat tatgctttgc tgtatgacca gttgctgtag
    25261 ttgtctcaag ggctgttgtt cttgtggatc ctgctgcaaa tttgatgaag acgactctga
    25321 gccagtgctc aaaggagtca aattacatta cacataaacg aacttatgga tttgtttatg
    25381 agaatcttca caattggaac tgtaactttg aagcaaggtg aaatcaagga tgctactcct
    25441 ttagattttg ttcgcgctac tgcaacgata ccgatacaag cctcactccc tttcggatgg
    25501 cttattgttg gcgttgcact tcttgctgtt tttcagagcg cttccaaaat cataaccctc
    25561 aaaaagagat ggcaactagc actctccaag ggtgttcact ttgtttgcaa cttgctgttg
    25621 ttgtttgtaa cagtttactc acaccttttg ctcgttgctg ctggccttga agcccctttt
    25681 ctctatcttt atgctttagt ctacttcttg cagagtataa actttgtaag aataataatg
    25741 aggctttggc tttgctggaa atgccgttcc aaaaacccat tactttatga tgccaactat
    25801 tttctttgct ggcatactaa ttgttacgac tattgtatac cttacaatag tgtaacttct
    25861 tcaattgtca ttacttcagg tgatggcaca acaagtccta tttctgaaca tgactaccag
    25921 attggtggtt atactgaaaa atgggaatct ggagtaaaag actgtgttgt attacacagt
    25981 tacttcactt cagactatta ccagctgtac tcaactcaat tgagtacaga cactggtgtt
    26041 gaacatgtta ccttcttcat ctacaataaa attgttgatg agcctgaaga acatgtccaa
    26101 attcacacaa tcgacggttc atccggagtt gttaatccag taatggaacc aatttatgat
    26161 gaaccgacga cgactactag cgtgcctttg taagcacaag ctgatgagta cgaacttatg
    26221 tactcattcg tttcggaaga gacaggtacg ttaatagtta atagcgtact tctttttctt
    26281 gctttcgtgg tattcttgct agttacacta gccatcctta ctgcgcttcg attgtgtgcg
    26341 tactgctgca atattgttaa cgtgagtctt gtaaaacctt ctttttacgt ttactctcgt
    26401 gttaaaaatc tgaattcttc tagagttcct gatcttctgg tctaaacgaa ctaaatatta
    26461 tattagtttt tctgtttgga actttaattt tagccatggc agattccaac ggtactatta
    26521 ccgttgaaga gcttaaaaag ctccttgaac aatggaacct agtaataggt ttcctattcc
    26581 ttacatggat ttgtcttcta caatttgcct atgccaacag gaataggttt ttgtatataa
    26641 ttaagttaat tttcctctgg ctgttatggc cagtaacttt agcttgtttt gtgcttgctg
    26701 ctgtttacag aataaattgg atcaccggtg gaattgctay cgcaatggct tgtcttgtag
    26761 gcttgatgtg gctcagctac ttcattgctt ctttcagact gtttgcgcgt acgcgttcca
    26821 tgtggtcatt caatccagaa actaacattc ttctcaacgt gccactccat ggcactattc
    26881 tgaccagacc gcttctagaa agtgaactcg taatcggagc tgtgatcctt cgtggacatc
    26941 ttcgtattgc tggacaccat ctaggacgct gtgacatcaa ggacctgcct aaagaaatca
    27001 ctgttgctac atcacgaacg ctttcttatt acaaattggg agcttcgcag cgtgtagcag
    27061 gtgactcagg ttttgctgca tacagtcgct acaggattgg caactataaa ttaaacacag
    27121 accattccag tagcagtgac aatattgctt tgcttgtaca gtaagtgaca acagatgttt
    27181 catctcgttg actttcaggt tactatagca gagatattac taattattat gaggactttt
    27241 aaagtttcca tttggaatct tgattacatc ataaacctca taattaaaaa tttatctaag
    27301 tcactaactg agaataaata ttctcaatta gatgaagagc aaccaatgga gattgattaa
    27361 acgaacatga aaattattct tttcttggca ctgataacac tcgctacttg tgagctttat
    27421 cactaccaag agtgtgttag aggtacaaca gtacttttaa aagaaccttg ctcttctgga
    27481 acatacgagg gcaattcacc atttcatcct ctagctgata acaaatttgc actgacttgc
    27541 tttagcactc aatttgcttt tgcttgtcct gacggcgtaa aacacgtcta tcagttacgt
    27601 gccagatcag cttcacctaa actgttcatc agacaagagg aagttcaaga actttactct
    27661 ccaatttttc ttattgttgc ggcaatagtg tttataacac tttgcttcac actcaaaaga
    27721 aagacagaat gattgaactt tcattaattg acttctattt gtgcttttta gcctttctgc
    27781 tattccttgt tttaattatg cttattatct tttggttctc acttgaactg caagatcata
    27841 atgaaatttg tcacgcctaa acgaacatga aatttcttgt tttcttagga atcatcacaa
    27901 ctgtagctgc atttcaccaa gaatgtagtt tacagtcatg tactcaacat caaccatatg
    27961 tagttgatga cccgtgtcct attcacttct attctaaatg gtatattaga gtaggagcta
    28021 gaaaatcagc acctttaatt gaattgtgcg tggatgaggc tggttctaaa tcacccattc
    28081 agtacatcga tatcggtaat tatacagttt cctgtttacc ttttacaatt aattgccagg
    28141 aacctaaatt gggtagtctt gtagtgcgtt gttcgttcta tgaagacttt ttagagtatc
    28201 atgacgttcg tgttgtttta gatttaatct aaacgaacaa actnaaatgt ctgataatgg
    28261 accccaaaat cagcgaaatg caccccgcat tacgtttggt ggaccctcag attcaactgg
    28321 cagtaaccag aatggagaac gcagtggggc gcgatcaaaa caacgtcggc cccaaggttt
    28381 acccaataat actgcgtctt ggttcaccgc tctcactcaa catggcaagg aaggccttaa
    28441 attccctcga ggacaaggcg ttccaattaa caccaatagc agtccagatg accaaattgg
    28501 ctactaccga agagctacca gacgaattcg tggtggtgac ggtaaaatga aagatctcag
    28561 tccaagatgg tatttctact acctaggaac tgggccagaa gctggacttc cctatggtgc
    28621 taacaaagac ggcatcatat gggttgcaac tgagggagcc ttgaatacac caaaagatca
    28681 cattggcacc cgcaatcctg ctaacaatgc tgcaatcgtg ctacaacttc ctcaaggaac
    28741 aacattgcca aaaggcttct acgcagaagg gagcagaggc ggcagtcaag cctcttctcg
    28801 ttcctcatca cgtagtcgca acagttcaag aaattcaact ccaggcagca gtatgggaac
    28861 ttctcctgct agaatggctg gcaatggctg tgatgctgct cttgctttgc tgctgcttga
    28921 cagattgaac cagcttgaga gcaaaatgtc tggtaaaggc caacaacaac aaggccaaac
    28981 tgtcactaag aaatctgctg ctgaggcttc taagaagcct cggcaaaaac gtactgccac
    29041 taaagcatac aatgtaacac aagctttcgg cagacgtggt ccagaacaaa cccaaggaaa
    29101 ttttggggac caggaactaa tcagacaagg aactgattac aaacattggc cgcaaattgc
    29161 acaatttgcc cccagcgctt cagcgttctt cggaatgtcg cgcattggca tggaagtcac
    29221 accttcggga acgtggttga cctacacagg tgccatcaaa ttggatgaca aagatccaaa
    29281 tttcaaagat caagtcattt tgctgaataa gcatattgac gcatacaaaa cattcccacc
    29341 aacagagcct aaaaaggaca aaaagaagaa ggcttatgaa actcaagcct taccgcagag
    29401 acagaagaaa cagcaaactg tgactcttct tcctgctgca gatttggatg atttctccaa
    29461 acaattgcaa caatccatga gcagtgctga ctcaactcag gcctaaactc atgcagacca
    29521 cacaaggcag atgggctata taaacgtttt cgcttttccg tttacgatat atagtctact
    29581 cttgtgcaga atgaattctc gtaactacat agcacaagta gatgtagtta actttaatct
    29641 cacatagcaa tctttaatca gtgtgtaaca ttagggagga cttgaaagag ccaccacatt
    29701 ttcaccgagg ccactcggag tacgatcgag tgtacagtga acaatgctag ggagagctgc
    29761 ctatatggaa gagccctaat gtgtaaaatt aattttagta gtgctatccc catgtgattt
    29821 taatagcttc ttagga")



# Решение заданий
puts "Минимальная специфичная для COVID (Ухань):"
puts find_min_unique_subsequence(covid_wuhan, h5n1)

puts "\nМинимальная специфичная для H5N1:"
puts find_min_unique_subsequence(h5n1, covid_wuhan)

puts "\nМинимальная общая для COVID и H5N1:"
puts find_common_subsequence(covid_wuhan, h5n1)

puts "Минимальная специфичная для COVID-Ухань (отсутствует в Дельта и H5N1):"
result_1 = find_min_unique(covid_wuhan, h5n1, covid_delta)
puts result_1

puts "\nМинимальная специфичная для COVID-Дельта (отсутствует в Ухань и H5N1):"
result_3 = find_min_unique(covid_delta, covid_wuhan, h5n1)
puts result_3

puts "\nМаксимальная общая подпоследовательность Ухань и Дельта:"
lcs_result = longest_common_subsequence(covid_wuhan, covid_delta)
ratio = lcs_result.length.to_f / covid_wuhan.length
puts lcs_result
puts "Длина: #{lcs_result.length}, Соотношение: #{(ratio * 100).round(2)}%"
